Bsr make components consistant
1024pix/pix-site pull request #150
Opened 2020-08-26 07:15 UTC by jbuget

## :unicorn: Problème

Le code commence à perdre en consistance dans le nommage de certaines propriétés, ou par rapport à un projet Prismic-Nuxt from scratch.

## :robot: Solution

- [x] Remonter le composant `SliceZone` directement sous `/components` comme quand on configure un projet Prismic-Nuxt avec la Slice Machine
- [x] Déplacer tous les composants de type Slice dans le répertoire `/components/slices`
- [x] Renommer pour chacun la propriété `:content` en `:slice` (comme un pour un projet de base)
- [ ] Renommer les composants pour qu'ils soient constitués de 2 mots minimum, en PascalCase, comme demandé par le CLI prismic.
- [ ] Renommer les champs Prismic pour qu'ils soient en snake_case (⚠️ touche aussi les models dans le CMS !)

![image](https://user-images.githubusercontent.com/265963/91272710-6f732700-e77c-11ea-9943-f90002677d53.png)

## :rainbow: Remarques

> _Des infos supplémentaires, trucs et astuces ?_

## :sparkles: Review App

https://pix-site-integration-pr.scalingo.io

2020-09-01 14:34 UTC, MelanieMEB requested changes
Proposition de BSR dans cette PR : 

Retirer dans Features : 
```
.features {
  background-color: white;
```
Car il pose problème dans certains cas (voir page Enseignement Sup)

2020-09-01 14:34 UTC, MelanieMEB commented on components/slices/PopInCampaigns.vue
> +          src="/static/images/close-icon.svg"
Pourquoi changer le lien vers l'image ? Cela semble ne pas s'afficher en review-app.

2020-09-02 08:16 UTC, MelanieMEB approved these changes

2020-09-02 08:22 UTC, alexandrecoin approved these changes

2020-09-02 08:26 UTC, sbedeau approved these changes

2020-09-02 08:27 UTC, merged