[FEATURE] Implémentation de la nouvelle barre de navigation (PIX-1071).
1024pix/pix-site pull request #166
Opened 2020-09-15 10:15 UTC by alexandrecoin

## :unicorn: Problème

Le site vitrine change de peau, donc la barre de navigation en haut doit faire peau neuve.

Attendu : 

https://app.abstract.com/projects/c43b8749-ba3a-474e-a6c5-dbf76bade2ee/branches/0f98f94c-8f44-4d4f-a988-72be104570aa/commits/latest/files/7CDCEB46-2B82-4218-B719-A559D817B735/layers/22F59764-AE99-4E92-8376-001C80AC08CF?collectionId=92047f7c-2ee2-4adc-9227-9b63f56bf55a&collectionLayerId=d4e6d1eb-18e3-452c-baf3-158576a9acfd

## :robot: Solution

- Remplacement des items de navigation de l'ancienne nav par les nouveaux provenant de Prismic
- Ajout d'une dropdown de sélection des élements de sous-navigation.

## :rainbow: Remarques

WIP : Ajouter une classe à l'élément parent de la dropdown (élément différent du reste sur la barre de navigation) afin de bénéficier des mêmes propriétés

## :sparkles: Review App
https://site-pr000.review.pix.fr/

2020-09-16 17:15 UTC, celineung commented on components/NavigationSliceZone.vue
> +        ...this.mainNavigation.data.body[1].items,
**suggestion** Voir ici pour se détacher de l'index du tableau

2020-09-21 09:08 UTC, MelanieMEB reviewed
Proposition d'amélioration. Sinon ça me parait bien. A tester sous IE avec Phili

2020-09-21 09:08 UTC, MelanieMEB commented on components/slices/NavigationZone.vue
> +    },
```suggestion
      const links = []
      this.slice.items.forEach((item) => {
        if (item.group.length > 0) {
          const groupName = item.group[0].text
          const alreadyGroupsInLinks = links.find((link)=> link.name==groupName && link.subNavigationLinks)
          if(!alreadyGroupsInLinks) {
            links.push({
              name: groupName,
              subNavigationLinks: [item],
            })
          } else {
            alreadyGroupsInLinks.subNavigationLinks.push(item)
          }
        } else {
          links.push(item);
        }
      })
      return links
    },
```

2020-09-21 14:22 UTC, MelanieMEB requested changes
Problème de sous-menu sous IE : Impossible de cliquer sur Enseignement Sup. Je pense que le clic pour sortir est pris au dessus du clic pour le lien.

2020-09-21 14:22 UTC, MelanieMEB commented on components/slices/NavigationZone.vue
> +        outline: none;
Je propose de retirer cette ligne pour avoir le focus visible sur le group en navigation clavier

2020-09-21 16:26 UTC, celineung commented on components/BurgerMenuNav.vue
> +  .nav-top a:hover {
```
.nav-top {
  &> a:hover {}
}
```

2020-09-21 16:26 UTC, celineung commented on components/BurgerMenuNav.vue
> +.navigation-slice-zone .bm-burger-button {
```
.navigation-slice-zone {
  &> bm-burger-button {}
}
```

2020-09-22 14:37 UTC, sbedeau requested changes
Retour func : il y a une ombre visible de chaque côté du menu que je n'ai pas trouvé dans la maquette

2020-09-22 14:37 UTC, sbedeau commented on components/BurgerMenuNav.vue
> +  @include device-is('large-screen') {
Pourquoi large-screen plutôt que desktop ?

2020-09-22 14:37 UTC, sbedeau commented on components/NavigationDropdown.vue
> +          console.log(event.target)
Est-ce qu'on a vraiment besoin de ce console.log ? 
Pourquoi le linter n'a pas réagit ?

2020-09-22 14:37 UTC, sbedeau commented on components/NavigationDropdown.vue
> +  font-weight: 400;
```suggestion
  font-weight: $font-normal;
```

2020-09-22 14:37 UTC, sbedeau commented on components/NavigationDropdown.vue
> +    0px 8px 32px 0px rgba(0, 0, 0, 0.06);
```suggestion
  box-shadow: 0 24px 32px 0 rgba(0, 0, 0, 0.03),
    0 8px 32px 0 rgba(0, 0, 0, 0.06);
```

2020-09-22 14:37 UTC, sbedeau commented on components/NavigationSliceZone.vue
> +    <div class="navigation-slice-zone">
Selon BEM, il faudrait plutôt 
```suggestion
  <div class="navigation-slice-zone">
    <div class="navigation-slice-zone__wrapper">
```

2020-09-22 14:37 UTC, sbedeau commented on components/NavigationSliceZone.vue
> +  grid-template-areas: '. navigation navigation navigation navigation navigation navigation navigation navigation navigation navigation navigation navigation .';
Pourquoi utiliser une grid ?

2020-09-22 14:37 UTC, sbedeau commented on components/slices/ActionsZone.vue
> +      font-weight: 500;
```suggestion
      font-weight: $font-medium;
```

2020-09-22 14:37 UTC, sbedeau commented on components/NavigationDropdown.vue
> +  background: white;
```suggestion
  background: $white;
```

2020-09-22 14:37 UTC, sbedeau commented on components/slices/LogosZone.vue
> +      return item.url.link_type !== 'Any'
Pour ma culture, c'est quoi Any ? Pourquoi Any plutôt que `!== null` ?

2020-09-22 14:37 UTC, sbedeau commented on components/slices/LogosZone.vue
> +      margin: 15px 0 9px 0;
Je pense que les margins asymétriques peuvent poser problème à la généricité du composant. 
Est-ce qu'on ne devrait pas plutôt imposer des logos sont un certain format via des margins symétriques fixes ?

2020-09-22 14:37 UTC, sbedeau commented on components/slices/NavigationZone.vue
> +    },
La complexité cyclomatique me semble très forte ici. Est-ce qu'on pourrait faire un découpage en courtes fonctions locales explicitement nommées ?

2020-09-22 14:37 UTC, sbedeau commented on components/BurgerMenuNav.vue
> +    height: 24px !important;
En général, `!important` est un bad smell. Comment est-ce qu'on peut l'enlever ?
```suggestion
    height: 24px;
```

2020-09-22 14:37 UTC, sbedeau commented on components/slices/NavigationZone.vue
> +      font-weight: 500;
```suggestion
      font-weight: $font-medium;
```

2020-09-22 14:43 UTC, celineung commented on components/slices/LogosZone.vue
> +      return item.url.link_type !== 'Any'
Prismic ne renvoit jamais `null` =/

2020-09-22 14:45 UTC, celineung commented on components/BurgerMenuNav.vue
> +  @include device-is('large-screen') {
d'après les maquettes, en desktop on a le burger menu
https://app.abstract.com/projects/c43b8749-ba3a-474e-a6c5-dbf76bade2ee/branches/0f98f94c-8f44-4d4f-a988-72be104570aa/collections/92047f7c-2ee2-4adc-9227-9b63f56bf55a

2020-09-22 14:45 UTC, celineung commented on components/NavigationDropdown.vue
> +          console.log(event.target)
c'est sur un commit de WIP, je debuggais le problème d'affichage sur IE

2020-09-22 14:52 UTC, celineung commented on components/NavigationSliceZone.vue
> +  grid-template-areas: '. navigation navigation navigation navigation navigation navigation navigation navigation navigation navigation navigation navigation .';
Pour avoir la navigation de la même taille que les éléments de la page

2020-09-22 15:01 UTC, celineung commented on components/BurgerMenuNav.vue
> +    height: 24px !important;
Je t'avoue ne pas avoir vu le `important` qui trainait.
En regardant de plus près, le `important` a été rajouté car le composant `vue-burger-menu` fait des manipulations directement sur l'élément sans passer par une classe css.
Je propose de voir cela lors de la refonte du burger-menu.

2020-09-22 16:23 UTC, celineung commented
> Retour func : il y a une ombre visible de chaque côté du menu que je n'ai pas trouvé dans la maquette

C'est fixé =)

2020-09-23 07:40 UTC, sbedeau commented on components/BurgerMenuNav.vue
> +  @include device-is('large-screen') {
Ça me semble être une mauvaise pratique d'avoir un burger menu en mode desktop

2020-09-23 07:43 UTC, sbedeau commented on components/NavigationSliceZone.vue
> +  grid-template-areas: '. navigation navigation navigation navigation navigation navigation navigation navigation navigation navigation navigation navigation .';
Je pense que ça amène un couplage fort sur le design et un couplage complexe dans le code. Je suggère de privilégier le flex pour garantir une maintenabilité simple

2020-09-23 07:52 UTC, celineung commented on components/NavigationSliceZone.vue
> +  grid-template-areas: '. navigation navigation navigation navigation navigation navigation navigation navigation navigation navigation navigation navigation .';
Mais en utilisant flex dans la navigation et grid dans les slices de page, ce n'est pas possible de les aligner

2020-09-23 07:53 UTC, sbedeau requested changes

2020-09-23 07:53 UTC, sbedeau commented on components/slices/NavigationZone.vue
> +  addNavigationLink(navigationLink) {
Est-ce que c'est bien une méthode locale ?
```suggestion
  _addNavigationLink(navigationLink) {
```

2020-09-23 07:53 UTC, sbedeau commented on components/slices/NavigationZone.vue
> +  addSubNavigationLink(groupName, subNavigationLink) {
Est-ce que c'est bien une méthode locale ?
```suggestion
  _addSubNavigationLink(groupName, subNavigationLink) {
```

2020-09-23 07:53 UTC, sbedeau commented on components/slices/NavigationZone.vue
> +      return navigation.links
Pourquoi est-ce qu'on a besoin d'un objet ? Il ne contient que links d'ailleurs
```suggestion
      return links
```

2020-09-23 07:53 UTC, sbedeau commented on components/slices/NavigationZone.vue
> +}
Je propose de mettre ces méthodes en fin de script pour suivre la step down rule et mettre en avant le script du fichier plutôt que les outils qui le compoosent

2020-09-23 07:54 UTC, sbedeau commented
Quelques commentaires ont aussi été rajoutés dans la review précédente

2020-09-23 07:54 UTC, celineung commented on components/slices/NavigationZone.vue
> +  addNavigationLink(navigationLink) {
Non, c'est une méthode publique

2020-09-23 07:54 UTC, celineung commented on components/slices/NavigationZone.vue
> +  addSubNavigationLink(groupName, subNavigationLink) {
Non, c'est une méthode publique

2020-09-23 07:55 UTC, celineung commented on components/slices/NavigationZone.vue
> +      return navigation.links
J'ai trouvé plus clair d'exporter la logique d'ajout dans le tableau dans un objet

2020-09-23 09:36 UTC, celineung commented
> Problème de sous-menu sous IE : Impossible de cliquer sur Enseignement Sup. Je pense que le clic pour sortir est pris au dessus du clic pour le lien.

c'est fixé =)

2020-09-24 14:00 UTC, MelanieMEB approved these changes

2020-09-24 14:00 UTC, MelanieMEB commented on components/BurgerMenuNav.vue
> +    g
Un g perdu :)

2020-09-25 10:05 UTC, merged