[FEATURE] Intégrer la sous-navigation de pix-pro (PIX-1265)
1024pix/pix-site pull request #178
Opened 2020-09-28 14:32 UTC by bpetetot

## :unicorn: Problème

Dans le cadre de la migration de pix-pro dans le répository de pix-site, la sous-navigation n'existe pas actuellement. Or pix-pro a besoin de cette barre de sous-navigation.

## :robot: Solution

Le but de cette PR est d'intégrer la barre de sous-navigation actuelle de pix-pro dans le repository pix-site. Nous n'avons pas retouché le design, car le but est d'être ISO avec le pix-pro actuel. Puis par suite (dans d'autre PR) nous retravaillerons le design et l'utilisation des composants slice dans cette navigation.

## :rainbow: Remarques

Désormais, côté Prismic, il est possible d'afficher ou non un logo (via le slice logo_zone) en fonction d'une propriété de l'API:
- `display_on_pix_site`: booléen qui affiche le logo sur pix-site
- `display_on_pix_pro`: booléen qui affiche le logo sur pix-pro

## :sparkles: Review App
https://site-pr000.review.pix.fr/
https://pro-pr000.review.pix.fr/

2020-09-29 09:36 UTC, frinyvonnick approved these changes

2020-09-29 09:36 UTC, frinyvonnick commented on components/BurgerMenuNav.vue
> +        <p>Pix Pro</p>
Ce paragraphe devrait être en dehors du `ul` 😄

2020-09-29 09:49 UTC, Laurentlcs approved these changes

2020-09-29 14:39 UTC, MelanieMEB reviewed
Globalement je valide.

Je me demande ce qu'on fait du "organization-nav" tant qu'on a pas le vrai bouton de switch de langue.

2020-09-29 14:39 UTC, MelanieMEB commented on components/OrganizationNav.vue
> -      <language-dropdown />
Je propose de garder quand même ce composant et son affichage, qui est le seul moyen actuellement de changer la langue.

2020-09-29 15:19 UTC, MelanieMEB requested changes

2020-09-29 15:19 UTC, MelanieMEB commented on components/OrganizationNav.vue
> -      <language-dropdown />
Après discussion, vu que c'est le seul moyen actuellement pour changer de langue et construire les pages en anglais, je propose de le laisser qu'avec le dropdown (et donc le `v-if="showLanguageDropdown` aussi)

2020-09-30 07:55 UTC, bpetetot commented on components/OrganizationNav.vue
> -      <language-dropdown />
Ok pas de soucis on s'occupe de ça ;) merci

2020-09-30 08:29 UTC, lisequesnel commented
Lorsqu'on est sur Pix Pro, ne devrait-on pas avoir `Pix Pro` souligné dans le menu principal, comme le sont les autres menus lorsqu'on se trouve dans leur rubrique ?

![image](https://user-images.githubusercontent.com/23451175/94661794-d2218a80-0307-11eb-98f3-c3b2c86fc09f.png)
![image](https://user-images.githubusercontent.com/23451175/94661833-dd74b600-0307-11eb-92c6-eb835c911792.png)

2020-09-30 08:59 UTC, bpetetot commented
> Lorsqu'on est sur Pix Pro, ne devrait-on pas avoir `Pix Pro` souligné dans le menu principal, comme le sont les autres menus lorsqu'on se trouve dans leur rubrique ?
> 
> ![image](https://user-images.githubusercontent.com/23451175/94661794-d2218a80-0307-11eb-98f3-c3b2c86fc09f.png)
> ![image](https://user-images.githubusercontent.com/23451175/94661833-dd74b600-0307-11eb-92c6-eb835c911792.png)

@lisequesnel En effet, car cet élément est souligné en utilisant en se basant sur nom de domaine (pro.pix.fr). C'est pourquoi on ne le voit pas souligné dans la review app. (c'est iso-fonctionnel par rapport à aujourd'hui)

2020-09-30 09:03 UTC, bpetetot commented on components/OrganizationNav.vue
> -      <language-dropdown />
En local et sur la review, sur pix-site et pix-pro, j'ai cette `OrganizationNav` qui s'affiche mais je ne vois jamais la liste des langues dans la barre. Du coup, elle est vide et ça fait bizarre.

J'ai donc 2 questions :
 - Est-ce qu'il me manque quelque chose pour faire apparaître la dropdown ?
 - Est-ce que je dois afficher la dropdown des langues sur pix-pro ?

![image](https://user-images.githubusercontent.com/516360/94665493-81f8f700-030c-11eb-997e-f7d10d1373f9.png)

2020-10-01 07:41 UTC, MelanieMEB approved these changes

2020-10-01 08:45 UTC, merged