[FEATURE] Création du bloc process (PIX-1198).
1024pix/pix-site pull request #179
Opened 2020-09-29 13:12 UTC by alexandrecoin

## :unicorn: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :robot: Solution
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :sparkles: Review App
https://site-pr000.review.pix.fr/
https://pro-pr000.review.pix.fr/

2020-09-30 07:43 UTC, Laurentlcs commented on components/slices/Process.vue
> +      )
```suggestion
      return this.slice.primary.process_title.length && this.slice.primary.process_title[0].text.length    
```
devrait suffire non ?  🤔

2020-09-30 07:43 UTC, Laurentlcs commented on components/slices/Process.vue
> +      )
Même proposition qu'au dessus

2020-10-01 07:52 UTC, MelanieMEB requested changes
Par rapport au passsage tablette : 
Sur l'exemple à 4 blocs sur Index, entre environ 1348 px et 960px, on a toujours les 4 blocs sur une lignes, mais ils dépassent sur les cotés pouvant les rendre illisble.

2020-10-01 07:52 UTC, MelanieMEB commented on components/slices/Process.vue
> +          <prismic-image v-if="hasImage(item)" :field="item.item_image" />
```suggestion
          <pix-image v-if="hasImage(item)" :field="item.item_image" />
```

2020-10-01 07:52 UTC, MelanieMEB commented on components/slices/Process.vue
> +      return this.slice.primary.process_display_title === 'Oui'
**Reflexion :** 
On a souvent mis des choses en anglais coté Prismic, pour avoir ensuite de l'anglais dans le code. Mais c'est possiblement moins utilisable coté Prismic pour la comm.
Est-ce qu'on ne devrait pas partir sur ça à l'avenir ?

2020-10-01 08:22 UTC, alexandrecoin commented on components/slices/Process.vue
> +      return this.slice.primary.process_display_title === 'Oui'
> Par rapport au passsage tablette :
> Sur l'exemple à 4 blocs sur Index, entre environ 1348 px et 960px, on a toujours les 4 blocs sur une lignes, mais ils dépassent sur les cotés pouvant les rendre illisble.

Il faut passer par le format d'affichage de devices mobiles du navigateur et recharger la page pour avoir le bon format.
La réduction de la taille de la fenêtre du navigateur ne permet pas de rendre les cartes dans le bon format puisque le nombre de lignes et de cartes qui les compose est calculée via une méthode (recalculée uniquement à chaque re-rendering du component) :/

2020-10-01 09:00 UTC, alexandrecoin commented on components/slices/Process.vue
> +      return this.slice.primary.process_display_title === 'Oui'
> **Reflexion :**
> On a souvent mis des choses en anglais coté Prismic, pour avoir ensuite de l'anglais dans le code. Mais c'est possiblement moins utilisable coté Prismic pour la comm.
> Est-ce qu'on ne devrait pas partir sur ça à l'avenir ?

Vu avec la comm, on peut tout passer en anglais.

2020-10-02 10:35 UTC, sbedeau requested changes
Tout n'est pas bloquant. On peut en discuter 

D'ailleurs, je réalise que j'aurais gagné en clarté et en empathie en appliquant [conventionnalcomments](https://conventionalcomments.org/) 💡
Je l'appliquerai la prochaine fois maintenant que j'ai développé une sensibilité pour son utilité, merci pour la tolérance ce coup ci 🙇

2020-10-02 10:35 UTC, ghost commented on components/slices/Process.vue
> +      v-if="displayTitle && hasTitle"
J'ai tendance à préférer l'ajout de `should` qui m'indique qu'il s'agit d'un booléen.

Pour la micro optimisation, j'inverserai le if (pas vraiment d'impact ici; de façon général, il est intéressant de prioriser la sortie du if par la probabilité d'état `false`)

```suggestion
      v-if="hasTitle && shouldDisplayTitle"
```

2020-10-02 10:35 UTC, ghost commented on components/slices/Process.vue
> +            />
Est-ce qu'on n'aurait pas naturellement un component `ProcessItem.vue` ici ?

2020-10-02 10:35 UTC, ghost commented on components/slices/Process.vue
> +        >
J'ai du mal à comprendre pourquoi on a besoin de deux boucles ici. Est-ce que tu pourrais m'en dire plus ? 
Est-ce qu'on ne peut pas gérer la deuxième boucle en CSS ?

2020-10-02 10:35 UTC, ghost commented on components/slices/Process.vue
> +} from '~/config/breakpoints'
Pourquoi ne pas utiliser directement les breakpoints définis dans la feuille scss dédiée ?

2020-10-02 10:35 UTC, ghost commented on components/slices/Process.vue
> +    useSubtitle() {
Par uniformité,
```suggestion
    displaySubtitle() {
```
ou 
```suggestion
    shouldDisplaySubtitle() {
```

2020-10-02 10:35 UTC, sbedeau commented on components/slices/Process.vue
> +      return this.slice.primary.process_display_title === 'Yes'
Pourquoi ne pas utiliser un booléen directement dans prismic ?

2020-10-02 10:35 UTC, sbedeau commented on components/slices/Process.vue
> +      return this.slice.primary.process_use_subtitle === 'Yes'
Pourquoi ne pas utiliser un booléen directement dans prismic ?

2020-10-02 10:35 UTC, sbedeau commented on components/slices/Process.vue
> +    },
Est-ce qu'il est possible d'exporter ce code quasi commun à feature dans un utils ?

2020-10-02 10:35 UTC, sbedeau commented on components/slices/Process.vue
> +        }
Je pense qu'on peut faire ça pour réduire la coxplexité cognitive

```suggestion
        if (this.items.length === 3 && isLargeScreen) {
          return 3
        }
        if (this.items.length === 4) {
          if (isExtraLargeScreen) {
            return 4
          }
          if (isLargeScreen) {
            return 3
          }
        }
        return 2
```
ou
```suggestion
		if(isLargeScreen) {
			if(this.items.length === 3) {
				return 3
			}
			if(this.items.length === 4) {
				return 4
			}
		}
        else if(isExtraLargeScreen) {
        	if(this.items.length === 4) {
        		return 4
        	}
        }
        else {
        	return 2
        }
```

2020-10-02 10:35 UTC, sbedeau commented on components/slices/Process.vue
> +      )
En lecture rapide, j'ai cru que c'était une méthode
```suggestion
      return Object.keys(item.item_image).length && item.item_image.constructor === Object
```
ou 
```suggestion
      return Object.keys(item.item_image).length &&
        item.item_image.constructor === Object
```
ou
```suggestion
	  const isLengthDifferentThanZero = Object.keys(item.item_image).length
	  const isObjectConstructor = item.item_image.constructor === Object
      return isLengthDifferentThanZero && isObjectConstructor
```

2020-10-02 10:35 UTC, sbedeau commented on components/slices/Process.vue
> +    font-weight: normal;
```suggestion
    font-weight: $font-normal;
```

2020-10-02 10:35 UTC, sbedeau commented on components/slices/Process.vue
> +    letter-spacing: 0.15px;
```suggestion
    letter-spacing: 0.009rem
```

2020-10-02 10:35 UTC, sbedeau commented on components/slices/Process.vue
> +    letter-spacing: 0.14px;
```suggestion
    letter-spacing: 0.009rem;
```

2020-10-02 10:35 UTC, sbedeau commented on components/slices/Process.vue
> +      margin-bottom: 0px;
```suggestion
      margin-bottom: 0;
```

2020-10-02 10:35 UTC, sbedeau commented on components/slices/Process.vue
> +      0px 8px 32px 0px rgba($black, 0.06);
```suggestion
    box-shadow: 0 24px 32px 0 rgba($black, 0.03),
      0 8px 32px 0 rgba($black, 0.06);
```

2020-10-02 10:35 UTC, sbedeau commented on components/slices/Process.vue
> +      margin-bottom: 0px;
```suggestion
      margin-bottom: 0;
```

2020-10-02 10:35 UTC, sbedeau commented on components/slices/Process.vue
> +  &-wrapper__row {
Ici on a un nouveau bloc. Je propose de le sortir du bloc parent pour suivre la convention Pix App et gagner en lisibilité

2020-10-02 10:35 UTC, sbedeau commented on components/slices/Process.vue
> +  &-wrapper__item {
Ici on a un nouveau bloc. Je propose de le sortir du bloc parent pour suivre la convention Pix App et gagner en lisibilité

2020-10-02 10:35 UTC, sbedeau commented on components/slices/Process.vue
> +  &-wrapper-item {
Ici on a un nouveau bloc. Je propose de le sortir du bloc parent pour suivre la convention Pix App et gagner en lisibilité

2020-10-02 10:35 UTC, sbedeau commented on components/slices/Process.vue
> +      font-weight: 600;
```suggestion
      font-weight: $font-semi-bold;
```

2020-10-02 10:35 UTC, sbedeau commented on components/slices/Process.vue
> +      letter-spacing: 0px;
```suggestion
      letter-spacing: 0;
```

2020-10-02 10:35 UTC, sbedeau commented on components/slices/Process.vue
> +      letter-spacing: 0px;
Je suis étonné qu'il n'y ait pas de letter-spacing d'ailleurs

2020-10-02 10:35 UTC, sbedeau commented on components/slices/Process.vue
> +      letter-spacing: 0.15px;
```suggestion
      letter-spacing: 0.009rem;
```

2020-10-02 10:35 UTC, sbedeau commented on components/slices/Process.vue
> +  }
```suggestion
  .process {
  	&__title h1 {
    	margin-top: 60px;
  	}

  	&__wrapper {
	    padding: 80px 0 84px;
	    display: flex;
	    flex-wrap: wrap;
	    justify-content: space-around;
	}
  }
```

2020-10-02 10:35 UTC, sbedeau commented on components/slices/Process.vue
> +    padding: 0px 98px 60px 98px;
```suggestion
    padding: 0 98px 60px 98px;
```

2020-10-02 10:35 UTC, sbedeau commented on components/slices/Process.vue
> +@include device-is('tablet') {
Je trouve que les includes me font perdre la lisibilité de la classe d'origine

2020-10-03 04:35 UTC, alexandrecoin commented on components/slices/Process.vue
> +} from '~/config/breakpoints'
Le problème ici est qu'il ne correspondent pas/plus aux breakpoints utilisés dans les maquettes.

2020-10-03 04:38 UTC, alexandrecoin commented on components/slices/Process.vue
> +    useSubtitle() {
Dans ce cas, nous ne souhaitons pas savoir si le sous-titre doit être affiché mais s'il doit être utilisé.
Si oui, je propose donc `shouldUseSubtitle` au lieu de `useSubtitle`.

2020-10-05 05:05 UTC, alexandrecoin commented on components/slices/Process.vue
> +        >
Le nommage des variables n'était en effet pas des plus explicites pour aider à la compréhension après relecture.
La structure de données étant : 

`[ [row0Item0, row0Item1], [row1Item0, row1Item1]]`

La première boucle s'occupe des lignes contenant [row0Item0, row0Item1] et [row1Item0, row1Item1].
La seconde des items `row0Item0, row0Item1, row1Item0 et row1Item1` en eux-mêmes.

2020-10-05 06:44 UTC, alexandrecoin commented on components/slices/Process.vue
> +            />
Je propose la création d'un nouveau ticket pour le processus de refacto, afin de mutualiser ce qui peut l'être pour Process et Features.

2020-10-05 06:44 UTC, alexandrecoin commented on components/slices/Process.vue
> +    },
Je propose la création d'un nouveau ticket pour le processus de refacto, afin de mutualiser ce qui peut l'être pour Process et Features.

2020-10-05 14:34 UTC, MelanieMEB approved these changes

2020-10-05 14:34 UTC, MelanieMEB commented on components/slices/Process.vue
> +            />
+1 pour un refacto plus tard, je pense qu'il faudra bien réfléchir à quoi refacto entre les différents blocs

2020-10-05 14:34 UTC, MelanieMEB commented on components/slices/Process.vue
> +    useSubtitle() {
Ok pour moi avec le `shouldUseSubtitle`, surtout qu'on reçoit un `process_use_subtitle`

2020-10-05 14:34 UTC, MelanieMEB commented on components/slices/Process.vue
> +@include device-is('tablet') {
A voir, car la maquette étant assez différente entre les devices, c'est bien aussi de pouvoir travailler device par device en ne modifiant que ce qui doit l'être.
J'ai peur que si on remette les include au dessus, ça sera aussi illisible.

2020-10-06 12:49 UTC, sbedeau approved these changes

2020-10-06 12:53 UTC, sbedeau requested changes
Retour fonctionnel : Broken en iPad pro 13" et laptop basse résolution 
<img width="1317" alt="Screenshot 2020-10-06 at 14 52 04" src="https://user-images.githubusercontent.com/46371288/95203872-9f820100-07e3-11eb-92ff-52a48ba783be.png">
<img width="1093" alt="Screenshot 2020-10-06 at 14 52 12" src="https://user-images.githubusercontent.com/46371288/95203881-a1e45b00-07e3-11eb-8f8b-0cc1e90ae0c5.png">

2020-10-06 15:29 UTC, alexandrecoin commented
> Retour fonctionnel : Broken en iPad pro 13" et laptop basse résolution

<img width="1274" alt="Capture d’écran 2020-10-06 à 17 28 04" src="https://user-images.githubusercontent.com/36371437/95222986-5e94e700-07f9-11eb-9535-925cd48fc960.png">

2020-10-07 10:17 UTC, sbedeau approved these changes
**praise:** Merci pour ta patience et la qualité des correctifs appliqués suite à une revue volumineuse et peu précise (sans conventionnal comments)

**suggestion:** Lorsque les bugs sont encapsulés dans un commit, il est plus facile d'apprendre dessus :)

**issue:** Il faut garder en tête que le resize nécessite un reload de la page pour que l'affichage se fasse correctement. Je n'ai pas de suggestion d'améliorations puisqu'on fait le changement au bon moment du cycle de vie du DOM. De toutes façons, il est peu probable que ce soit un comportement utilisateur normal / fréquent

2020-10-07 11:03 UTC, alexandrecoin commented
Merci pour tes retours. 🙏

A savoir que le comportement du resize est le même sur Features, où le souci est moins/non visible du fait de la non encapsulation du contenu dans des cards.
Mais totalement d'accord avec toi sur le fait que ce comportement de la part d'un utilisateur n'ait pas ou peu de raison d'exister en dehors d'un changement de taille d'écran via l'inspecteur de la console. 🧐

**Note to self** : Mieux vérifier les différents formats et relire le code avec un davantage de recul avant demande de review à l'avenir.

2020-10-07 11:14 UTC, merged