[TECH] Amélioration du temps de chargement des pages.
1024pix/pix-site pull request #180
Opened 2020-09-30 15:07 UTC by VincentHardouin

## :unicorn: Problème
En regardant sur [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?hl=fr&url=pix.fr), j'ai pu voir que le score n'était pas excellent. J'ai alors cherché à l'améliorer. 

<img width="1062" alt="Screenshot 2020-09-30 at 16 53 08" src="https://user-images.githubusercontent.com/26384707/94701879-6fe37c80-033d-11eb-88cb-9a62e81dc7a4.png">

## :robot: Solution
### 🌮  Tester sur PageSpeed Insights mon environnement local
Je voulais pouvoir tester rapidement mon environnement local sur PageSpeed Insights. 
Pour cela : 
1. Je lance un [ngrok](https://ngrok.com/) avec la commande `ngrok http 5000` (5000 étant le port de pix-site) 
Cela me permets de récupérer une adresse redirigeant vers mon `localhost`
<img width="599" alt="Screenshot 2020-09-30 at 16 58 11" src="https://user-images.githubusercontent.com/26384707/94702508-221b4400-033e-11eb-8584-def4f8744602.png">

2. Je lance mon application comme en production : `npm run build:site && npm run start:site`
3. Je peux fournir l'adresse fournie par ngrok sur PageSpeed Insights. 

### 🗑️ Supprimer le code inutile 
J'ai dans un premier temps regardé les requêtes HTTP lors du chargement du https://pix.fr, on voit un appel en status 404 sur `https://pix.fr/undefined`. 
J'ai réussi à enlever cet appel en enlevant tout le style présent dans le fichier `index.vue`

### 🚀 Améliorer l'existant

Dans le [compte rendu](https://developers.google.com/speed/pagespeed/insights/?hl=fr&url=pix.fr), on peut voir cette section : 
<img width="733" alt="Screenshot 2020-09-30 at 16 40 24" src="https://user-images.githubusercontent.com/26384707/94700379-ae783780-033b-11eb-844b-fce5610dd3e6.png">

Pour résoudre ce problème il faut utiliser la propriété [font-display: swap](https://developer.mozilla.org/fr/docs/Web/CSS/@font-face/font-display)
Seulement on peut le faire directement dans l'url allant chercher les polices de Google : 
```
https://fonts.googleapis.com/css2?family=Open+Sans:300,400,500,600,700,400i|Roboto:400,500,600&display=swap
```

#### 💯  Gains obtenus

<img width="1054" alt="Screenshot 2020-09-30 at 17 06 56" src="https://user-images.githubusercontent.com/26384707/94703654-5c391580-033f-11eb-960b-7453495aa9e9.png">

 

## :rainbow: Remarques
J'ai tenté de faire du [lazy-loading](https://medium.com/@BiigDigital/lazy-loading-3130159ef205) en utilisant un [plugin nuxt](https://www.npmjs.com/package/nuxt-lazy-load), mais j'avais l'impression que les résultats n'étaient pas probant. 

## :sparkles: Review App
https://site-pr000.review.pix.fr/
https://pro-pr000.review.pix.fr/

2020-10-01 08:21 UTC, jbuget approved these changes
👏

2020-10-01 08:21 UTC, jbuget commented on nuxt.config.js
> +          'https://fonts.googleapis.com/css2?family=Open+Sans:300,400,500,600,700,400i|Roboto:400,500,600&display=swap',
**praise:** https://developers.google.com/fonts/docs/css2

2020-10-01 09:59 UTC, sbedeau requested changes
Bravo pour cette PR et notamment le `font-display : swap` ! 👏 
Je remarque cependant qu'il y a du CSS qui était utilisé et qui a été supprimé. Je propose soit : 
- de remettre la suppression du CSS à après un petit nettoyage suite aux chantiers en cours sur pix-site qui nous obligent à faire des changements doux
- de faire effectivement une passe globalement dans cette PR

2020-10-01 10:07 UTC, laura-bergoens approved these changes
J'approuve aussi car c'est super cool comme démarche, sous couvert que tu répondes aux interrogations de @sbedeau

2020-10-02 11:58 UTC, sbedeau approved these changes

2020-10-05 07:32 UTC, merged