[FEATURE] Ajouter un nouveau slice logos
1024pix/pix-site pull request #186
Opened 2020-10-07 09:53 UTC by celineung

## :unicorn: Problème
Dans le cadre de la refonte du site vitrine, on souhaiterait avoir des blocs réutilisables.

## :robot: Solution
Créer la nouvelle slice Logos

## :rainbow: Remarques
Dans la nouvelle navigation: on a un composant qui s'appelle `LogosZone`.
Dans une page, on peut ajouter un composant `Logos`.
Qu'est-ce que vous pensez du nommage?
Pour clarifier on peut renommer:
- soit le premier en `NavigationLogosZone` (du coup préfixer tous les noms des composants de la navigation par `Navigation`)
- soit le 2e en `PartnerLogos` mais est-ce que cette slice sera toujours utiliser pour y mettre des logos partner?

## :sparkles: Review App
https://site-pr000.review.pix.fr/
https://pro-pr000.review.pix.fr/

2020-10-08 09:57 UTC, sbedeau requested changes
Ça m'a l'air ok fonctionnellement

2020-10-08 09:57 UTC, sbedeau commented on components/slices/Process.vue
> +  .wrapper {
**suggestion (blocking):** Cette suggestion vous permet de respecter BEM sans encapsulation

```suggestion
  .process-wrapper {
```

2020-10-08 09:57 UTC, sbedeau commented on components/slices/Logos.vue
> +    .wrapper {
```suggestion
    .logos-wrapper {
```

2020-10-08 09:57 UTC, sbedeau commented on components/slices/Logos.vue
> +  .wrapper__item {
```suggestion
  .logos-wrapper__item {
```

2020-10-08 09:57 UTC, sbedeau commented on components/slices/Logos.vue
> +    .wrapper__item {
```suggestion
    .logos-wrapper__item {
```

2020-10-09 07:31 UTC, MelanieMEB approved these changes
OK pour moi avec le renommage proposé par Steph pour éviter tout conflit.

2020-10-12 15:53 UTC, sbedeau requested changes
**nitpick (blocking):** Il y a une hétérogénéité entre `PartnerLogos` (Logos partenaires) et `PartnersLogos` (Logo des partenaires). Les deux sont correctes, à voir ce qui représente le plus le métier.

2020-10-12 15:53 UTC, sbedeau commented on components/SliceZone.vue
> +      </template>
```suggestion
      <template v-if="slice.slice_type === 'partner_logos'">
        <partner-logos-slice :slice="slice" />
      </template>
```

2020-10-12 15:53 UTC, sbedeau commented on components/SliceZone.vue
> +import PartnersLogosSlice from '@/components/slices/PartnerLogos'
```suggestion
import PartnerLogosSlice from '@/components/slices/PartnerLogos'
```
ou 
```suggestion
import PartnersLogosSlice from '@/components/slices/PartnersLogos'
```

2020-10-12 15:53 UTC, sbedeau commented on components/slices/PartnerLogos.vue
> +  name: 'PartnersLogosSlice',
```suggestion
  name: 'PartnerLogosSlice',
```

2020-10-12 15:53 UTC, sbedeau commented on components/slices/PartnerLogos.vue
> +}
**nitpick(non-blocking) :** Je pense qu'on peut les sortir de l'imbrication pour mieux respecter BEM et aplatir la structure du CSS

2020-10-12 15:53 UTC, sbedeau commented on components/slices/Process.vue
> +      }
**nitpick(non-blocking) :** Je pense qu'on peut les sortir de l'imbrication pour mieux respecter BEM et aplatir la structure du CSS

2020-10-12 16:09 UTC, celineung commented on components/slices/PartnerLogos.vue
> +}
C'est-à-dire pour avoir quelque chose comme:
```css
.logos { ... }
.logos {
  @include device-is('tablet') { ... }
}
.logos {
  @include device-is('desktop') { ... }
}
```
?

2020-10-12 19:11 UTC, alexandrecoin commented on components/slices/PartnerLogos.vue
> +  name: 'PartnersLogosSlice',
Je pense que `PartnersLogos` est un peu plus proche de la réalité au niveau de la traduction. 
Il ne s'agit pas du 's de possession mais du pluriel, traduisible donc par "Logos des partenaires", là où 'PartnerLogos" aurait pour traduction "Logos du partenaire".

2020-10-12 19:42 UTC, alexandrecoin commented on components/slices/Process.vue
> +      }
Et du coup obtenir quelque chose comme : 
```  
.process { ... }

.process-wrapper { ... }

.process-wrapper-item { ... }
```
?

2020-10-12 19:43 UTC, alexandrecoin commented on components/slices/PartnerLogos.vue
> +}
Même question que @celineung .

2020-10-13 09:04 UTC, celineung commented on components/slices/PartnersLogos.vue
> +.logos {
**suggestion**: renommer `logos` en `partners-logos`

2020-10-13 12:44 UTC, sbedeau approved these changes

2020-10-13 13:11 UTC, jonasgrilleres approved these changes

2020-10-13 13:53 UTC, merged