[BUGFIX] Correction des tailles d'images pour le MultipleBlock (PIX-1530).
1024pix/pix-site pull request #206
Opened 2020-10-27 15:09 UTC by alexandrecoin

## :unicorn: Problème

Les images des blocs Process, Stats et Features qu'il est possible de réaliser n'ont pas la même taille.
Or le block était défini sur Prismic avec une taille d'image de 51px X 51px  pour les trois types de blocs, causant des rognages sur certains blocs lorsque les images étaient trop grandes/larges.

## :robot: Solution

- Modification du Custom Type sur Prismic avec une taille auto correspondant à la taille originelle de l'image importée.
- Ajout de CSS pour fixer la taille des images dans les blocs où cela est nécessaire.

## :100: Pour tester

2020-10-27 15:10 UTC, pix-service commented
I'm deploying this PR to these urls:

- Pix Site (fr): https://site-pr206.review.pix.fr
- Pix Site (org): https://site-pr206.review.pix.org
- Pix Pro (fr): https://pro-pr206.review.pix.fr
- Pix Pro (org): https://pro-pr206.review.pix.org

 Please check it out!

2020-10-28 13:22 UTC, MelanieMEB requested changes
Le problème semble encore présent sur les images, sur la page enseignement-scolaire2 (passer par Prismic pour voir la page en construction), dans la partie "Une innovation pédagogique"

2020-10-30 09:57 UTC, MelanieMEB approved these changes

2020-11-02 09:19 UTC, celineung approved these changes

2020-11-02 09:40 UTC, merged