[FEATURE] Redesign du menu burger (PIX-2257).
1024pix/pix-site pull request #249
Opened 2021-03-02 14:25 UTC by alexandrecoin

## :unicorn: Problème

Le menu de navigation burger n'a pas été soumis au même traitement que le reste de Pix-Site et Pix-Pro.

## :robot: Solution

Nouvelle intégration du menu pour mieux correspondre à ce qu'il est possible de retrouver sur les [maquettes correspondantes](https://app.abstract.com/projects/c43b8749-ba3a-474e-a6c5-dbf76bade2ee/branches/bebfc077-344c-493f-b5d9-5af739007f4c/collections/4ba0a963-0c56-4a4d-a624-50ab00fb671a).

## :rainbow: Remarques

Plusieurs points sont à noter : 

- Nous avons choisi, et contrairement à ce qu'il est possible de retrouver sur les maquettes, de ne pas intégrer les logos de Pix et République Française car depuis la PR #247 , les icônes ne se déplacent plus lorsque l'on ouvre le menu, les laissant ainsi apparaitre une fois le menu ouvert, les rendant redondants. A cela s'ajoute une intégration non aisée liée à l'utilisation de la librairie `vue-burger-menu`.

- Nous avons modifié l'organisation des données passées en `props` au composant `BurgerMenuNav` afin de les rendre plus facilement utilisables et de mieux accentuer la séparation entre ce est `lien` et 'action` (ex: Enseignement Scolaire VS S'inscrire). 
Cela nous incite toutefois à une répétition de la création de la liste `<ul>` dans le composant de par la pluralité nouvellement créée des données passée à la liste.

- Il nous est possible de mieux correspondre à BEM en ce qui concerne le nommage des classes CSS, en ajoutant par exemple aux listes `<ul>` la classe `class="burger-navigation__links` qui n'apporterait toutefois pas grand chose, à part servir de container aux liens que la liste contient.

## :100: Pour tester

Aller sur Pix-site (.fr et .org) et Pix-Pro, et vérifier que l'intégration correspond aux maquettes proposées.

2021-03-02 14:26 UTC, pix-service commented
I'm deploying this PR to these urls:

- Pix Site (fr): https://site-pr249.review.pix.fr
- Pix Site (org): https://site-pr249.review.pix.org
- Pix Pro (fr): https://pro-pr249.review.pix.fr
- Pix Pro (org): https://pro-pr249.review.pix.org

 Please check it out!

2021-03-03 10:26 UTC, celineung reviewed
✅ sur IE

Il y a quelques comportements bizarres mais qui étaient déjà là avant.
Je note là mais c'est à traiter dans une autre PR:
- le burger menu ne se ferme pas lorsqu'un élément du menu a été cliqué et que l'utilisateur est redirigé vers la page demandé
- lorsque le burger est ouvert, l'opacité en background ne se met que sur la navigation
- certaines pages sont toutes cassées sous IE (ex: enseignement scolaire) 😢

2021-03-03 10:26 UTC, celineung commented on components/BurgerMenuNavItems.vue
> +  <ul class="burger-menu-nav__items">
Pour suivre le nom du fichier:

```suggestion
  <ul class="burger-menu-nav-items">
```

2021-03-03 10:26 UTC, celineung approved these changes

2021-03-04 09:34 UTC, MelanieMEB approved these changes

2021-03-04 10:41 UTC, sbedeau requested changes
**praise:** C'est un gros morceau, bien joué ! 🎉

2021-03-04 10:41 UTC, sbedeau commented on components/BurgerMenuNav.vue
>  .navigation-slice-zone {
**question:** À quoi sert la définition de la classe `navigation-slice-zone` ici ?

2021-03-04 10:41 UTC, sbedeau commented on components/BurgerMenuNavItems.vue
> +    action: {
**suggestion(non-blocking):** Expliciter la nature booléenne de cette variable par l'ajout d'un verbe
```suggestion
    isAction: {
```

2021-03-04 10:41 UTC, sbedeau commented on components/BurgerMenuNavItems.vue
> +      default: null,
**issue:** Par défaut, un booléen doit conserver sa nature et être soit true, soit false pour éviter des comportements hasardeux

2021-03-04 10:41 UTC, sbedeau commented on components/BurgerMenuNavItems.vue
> +  }
**suggestion(non-blocking):** Regrouper ces lignes avec le `&:last-child` défini en ligne 42

2021-03-04 10:41 UTC, sbedeau commented on components/NavigationSliceZone.vue
> +      <slide-menu width="320" class="burger-menu">
**question:** Pourquoi ne pas ajouter la `width` dans la classe `burger-menu` ?
```suggestion
      <slide-menu class="burger-menu">
```

2021-03-04 10:41 UTC, sbedeau commented on components/NavigationSliceZone.vue
> +        </section>
**question:** Quel était le besoin de sortir la section de la div encapsulante ?

2021-03-04 10:41 UTC, sbedeau commented on components/NavigationSliceZone.vue
> +      <div class="navigation-slice-zone__content">
**question:** Cette `div` contient uniquement une `section`. Est-ce que la `div` est encore utile ?

2021-03-04 10:41 UTC, sbedeau commented on components/NavigationSliceZone.vue
> +          class="navigation-slice-zone-wrapper__right-side"
**nitpick(~blocking):** Pour assurer la cohérence du scss, je renommerai comme ça 
```suggestion
          class="navigation-slice-zone-content__right-side"
```

2021-03-04 10:41 UTC, sbedeau commented on components/slices/ActionsZone.vue
> +    line-height: 22px;
```suggestion
    letter-spacing: 0.008rem;
    line-height: 1.375rem;
```

2021-03-04 12:06 UTC, alexandrecoin commented on components/NavigationSliceZone.vue
> +        </section>
Afin de pouvoir mettre le bouton de connexion en mode mobile/tablette sur le côté droit de l'écran et profiter du `justify-content: space-between;` nouvellement créé.

2021-03-04 12:06 UTC, alexandrecoin commented on components/NavigationSliceZone.vue
> +      <div class="navigation-slice-zone__content">
Bien vu.

2021-03-04 12:07 UTC, alexandrecoin commented on components/NavigationSliceZone.vue
> +      <slide-menu width="320" class="burger-menu">
Il s'agit d'une `props` définie par `vue-burger-menu`[documentation](https://github.com/mbj36/vue-burger-menu#width)

2021-03-04 12:13 UTC, alexandrecoin commented on components/BurgerMenuNav.vue
>  .navigation-slice-zone {
Elle sert  de wrapper aux propriétés définies à l'intérieur et qui concernent toutes le CSS du menu burger.

2021-03-04 13:38 UTC, sbedeau approved these changes

2021-03-04 13:38 UTC, sbedeau commented on components/BurgerMenuNav.vue
>  .navigation-slice-zone {
Est-ce que ça ne devrait pas être `.burger-menu-nav` ?

2021-03-04 14:26 UTC, alexandrecoin commented on components/BurgerMenuNav.vue
>  .navigation-slice-zone {
Ca casse avec le `.burger-menu-nav` pour une raison qui m'échappe mais passe pour son parent direct, à savoir `.burger-menu`

2021-03-04 14:37 UTC, merged