[BUGFIX] Bouton `appel a l'action` sur mobile.
1024pix/pix-site pull request #295
Opened 2021-08-20 13:39 UTC by Thomasevano

## :unicorn: Problème
Les cta button sur pix-site sont coupés en deux sur mobile
<img width="486" alt="Capture d’écran 2021-08-20 à 14 53 46" src="https://user-images.githubusercontent.com/22095896/130236223-69ccce72-d31d-4d35-b9f6-fc3b8faa5aad.png">

## :robot: Solution
ajouter une classe `button-container` avec la propriété `width: max-content` a la div contenant le bouton.

## :rainbow: Remarques
Cela est une solution temporaire que je propose qui permet d'avoir le bouton sur une ligne complete, cela rend plus ou moins bien suivant la longeur du texte dans le bouton.
Vos suggestions sont les bienvenues.

## :100: Pour tester
Naviguer sur les différentes pages en mobile et voir que le bouton s'affiche d'une manière lisible.

2021-08-20 13:41 UTC, pix-service commented
I'm deploying this PR to these urls:

- Pix Site (fr): https://site-pr295.review.pix.fr
- Pix Site (org): https://site-pr295.review.pix.org
- Pix Pro (fr): https://pro-pr295.review.pix.fr

 Please check it out!

2021-08-20 14:43 UTC, thetinyspark approved these changes
seems good to me

2021-08-20 14:48 UTC, celineung approved these changes

2021-08-20 16:28 UTC, sbedeau requested changes

2021-08-20 16:28 UTC, sbedeau commented on components/slices/Article.vue
> +  }
**chipotage (bloquant):** Cette classe doit suivre BEM et porter un nom en conséquence : 

```suggestion
  &__button-container {
    width: max-content;
  }
```

2021-08-23 09:56 UTC, MelanieMEB requested changes
Soucis Fonctionnel : Quand je test à 300 px (ce n'est pas beaucoup, mais c'est la taille mini pour les tests mobiles), je n'ai plus de soucis mais par contre le texte déborde de l'écran, et je ne peux pas lire le texte du bouton :s

2021-08-23 10:46 UTC, Thomasevano commented
> Soucis Fonctionnel : Quand je test à 300 px (ce n'est pas beaucoup, mais c'est la taille mini pour les tests mobiles), je n'ai plus de soucis mais par contre le texte déborde de l'écran, et je ne peux pas lire le texte du bouton :s

Ah oui 300 carrément, c'est vraiment petit, le minimum que j'ai testé c'est 320px en effet 1 ou 2 textes dépasse un peu car il sont très long ca arrive aussi avec d'autres liens :(

2021-08-31 14:36 UTC, MelanieMEB approved these changes

2021-09-01 06:36 UTC, VincentHardouin approved these changes

2021-09-01 07:43 UTC, Thomasevano reviewed
**Suggestion:** Dans le `article_content--only-text` il y a un `width:65px` qui je trouve ne sert pas a grand chose

2021-09-02 07:51 UTC, sbedeau approved these changes

2021-09-02 08:01 UTC, Thomasevano commented
Je viens de voir que les boutons sont aussi modifier en desktop, est-ce que l'on mettrait pas le `display:flex` juste en mobile

2021-09-02 12:22 UTC, alexandrecoin commented
> Je viens de voir que les boutons sont aussi modifier en desktop, est-ce que l'on mettrait pas le `display:flex` juste en mobile, afin de garder l'affichage normal en tablette et desktop ?
> 
> **Suggestion:** rajouter quelque chose comme ça
> `@include device-is('tablet') { .cta-button { display: initial; } }`

On va passer ça dans une autre PR je pense, celle-ci est restée ouverte bien assez longtemps. 😅

2021-09-02 12:24 UTC, merged