[TECH] Mettre à jour les dépendances
1024pix/pix-site pull request #306
Opened 2021-10-28 10:42 UTC by VincentHardouin

## :unicorn: Problème
Les dépendances ne sont pas à jour

## :robot: Solution
Faire les montées de version.

`babel-eslint` est désormais déprécié, je l'ai donc remplacé par `@babel/eslint-parser` (cf: https://www.npmjs.com/package/babel-eslint) 

Updated packages :

Package|Old|New
-|-|-
@fortawesome/fontawesome-svg-core|1.2.35|1.2.36
@fortawesome/free-solid-svg-icons|5.15.3|5.15.4
@fortawesome/vue-fontawesome|2.0.2|2.0.6
[@nuxtjs/eslint-config](https://github.com/nuxt/eslint-config/releases)|6.0.1|7.0.0
@nuxtjs/style-resources|1.2.0|1.2.1
@vue/test-utils|1.2.1|1.2.2
autoprefixer|10.2.6|10.3.7
[babel-jest](https://github.com/facebook/jest/blob/main/CHANGELOG.md)|26.6.3|27.3.1
[eslint](https://github.com/eslint/eslint/blob/main/CHANGELOG.md)|7.29.0|8.1.0
[eslint-plugin-nuxt](https://github.com/nuxt/eslint-plugin-nuxt/blob/master/CHANGELOG.md)|2.0.0|3.0.0
[eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier/blob/master/CHANGELOG.md)|3.4.0|4.0.0
nuxt-i18n|6.27.2|6.28.1
postcss-cli|8.3.1|9.0.1
prettier|2.3.2|2.4.1
jest|27.0.6|27.3.1

Packages not updated :
- nuxt
- chart.js

## :rainbow: Remarques
- La version de nuxt ne monte pas facilement alors que c'est des patchs. J'ai trouvé [cette issue](https://github.com/nuxt/nuxt.js/issues/6823#issuecomment-568435309), je propose de le faire dans une autre PR. 

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2021-10-28 12:57 UTC, pix-service commented
I'm deploying this PR to these urls:

- Pix Site (fr): https://site-pr306.review.pix.fr
- Pix Site (org): https://site-pr306.review.pix.org
- Pix Pro (fr): https://pro-pr306.review.pix.fr

 Please check it out!

2021-10-28 14:22 UTC, yannbertrand approved these changes

2021-10-28 14:38 UTC, MelanieMEB requested changes
Bug apparu : problème lors du lancement des vidéo de présentation.
`t._ssrNode is not a function`

2021-10-28 15:21 UTC, VincentHardouin commented
> Bug apparu : problème lors du lancement des vidéo de présentation. `t._ssrNode is not a function`

Cela devrait être bon.

2021-11-02 10:43 UTC, MelanieMEB approved these changes

2021-11-03 10:05 UTC, merged