[FEATURE] Ajouter le menu Switch de langue sur le .org (PIX-4038)
1024pix/pix-site pull request #349
Opened 2021-12-29 14:14 UTC by squirrel4k

## :unicorn: Problème
Modifier le menu pour le choix de la langue du site.

## :robot: Solution
- Modifier le scss
- Modifier le composant
- Update des fichiers de traduction

## :rainbow: Remarques
Le menu mobile n'est pas encore décidé.

## :100: Pour tester
Vérifier le menu sur un url.org

2021-12-29 14:15 UTC, pix-service commented
I'm deploying this PR to these urls:

- Pix Site (fr): https://site-pr349.review.pix.fr
- Pix Site (org): https://site-pr349.review.pix.org
- Pix Pro (fr): https://pro-pr349.review.pix.fr

 Please check it out!

2022-01-03 09:52 UTC, MelanieMEB requested changes
**FuncReview** : Sur le menu, il y a un retour vers "France" qui renvoit vers le .org/fr, alors qu'il devrait renvoyer vers le .fr

2022-01-03 10:01 UTC, squirrel4k commented
> **FuncReview** : Sur le menu, il y a un retour vers "France" qui renvoit vers le .org/fr, alors qu'il devrait renvoyer vers le .fr

Du coup, comment on atteint le /fr ?

2022-01-03 11:05 UTC, MelanieMEB requested changes

2022-01-03 11:05 UTC, MelanieMEB commented on components/LanguageSwitcher.vue
> +          <span v-if="!option.target">
Amélioration a11y : Ce span simple est plutôt un bouton, vu qu'il permet d'afficher la liste des langues. Ou voir si, avec le clavier, on ne peut pas directement rentrer dans les sous-menu.
Besoin : changer la langue au clavier

2022-01-03 11:05 UTC, MelanieMEB commented on components/LanguageSwitcher.vue
> +        //overflow: hidden;
Commentaire à retirer avant MeP

2022-01-03 11:05 UTC, MelanieMEB commented on components/LanguageSwitcher.vue
> +        //color: $blue;
Commentaire à retirer avant MeP

2022-01-03 11:05 UTC, MelanieMEB commented on components/LanguageSwitcher.vue
> +      //height: auto;
Commentaire à retirer avant MeP

2022-01-03 11:05 UTC, MelanieMEB commented on static/images/flag-be.svg
> +<?xml version="1.0" encoding="UTF-8"?>
Info : Pour les SVG, on utilise souvent svgo (https://github.com/svg/svgo) qu'on lance sur nos svg pour les réduire et les nettoyer un peu.

2022-01-05 09:21 UTC, yannbertrand commented on components/LanguageSwitcher.vue
> +      showInternational: false,
Inutilisé ?

2022-01-05 09:26 UTC, squirrel4k commented on components/LanguageSwitcher.vue
> +      showInternational: false,
En effet, showInternational n'est pas utilisé.  J'enlève çà de suite :)!

2022-01-05 09:28 UTC, yannbertrand commented on components/LanguageSwitcher.vue
> +      languages,
**suggestion:** Si je comprend bien `languages` remplace `languageLocales`.

Je trouve le nom `languageLocales` plus adapté car on mix les langues et l'endroit sur la planète.

Le code au dessus pour récupérer les `availableLocales` et `languageLocales` n'a probablement plus de sens également si ce n'est plus suffisant pour notre besoin.

2022-01-05 10:45 UTC, yannbertrand commented on config/language.js
> +export const languageMenu = [
Ça me plait bien d'ajouter ces infos dans un fichier externe mais est-ce qu'on ne peut pas centraliser ces infos et s'en servir également dans la liste des locales i18n du nuxt.config.js ?

2022-01-07 09:31 UTC, alexandrecoin commented on config/language.js
> +export const languageMenu = [
Cela surchargerait le fichier de config sans réelle valeur ajoutée amha.

2022-01-07 09:48 UTC, alexandrecoin commented on components/LanguageSwitcher.vue
> +      languages,
Je ne suis pas sûr de comprendre. 
De ce que j'ai pu voir, je n'ai pas l'impression qu'il soit question de remplacement de la part de `languages` et `languageLocales`. Les objets diffèrent dans leur conception.

2022-01-11 09:24 UTC, yannbertrand commented on config/language.js
> +export const languageMenu = [
Précision : il s'agit de regrouper les infos de locales i18n vers un fichier de config des langues (non l'inverse désolé pour l'imprécision :)).

Discuté ensemble, à voir dans une autre PR !

2022-01-11 09:24 UTC, yannbertrand commented on components/LanguageSwitcher.vue
> +      languages,
En fait `languageLocales` est toujours utilisé dans les `computed` donc probablement plus complexe que prévu. A voir dans une autre PR !

2022-01-11 09:28 UTC, yannbertrand commented on config/language.js
> +    process.env.SITE === 'pix-pro'
```suggestion
    process.env.SITE === SITES_PRISMIC_TAGS.PIX_PRO
```

2022-01-11 09:40 UTC, alexandrecoin approved these changes

2022-01-11 10:15 UTC, nlepage commented on config/language.js
> +      target: false,
```suggestion
      target: null,
```

2022-01-11 10:25 UTC, nlepage commented on components/LanguageSwitcher.vue
> +            @click.stop.prevent
```suggestion
            @click.stop.prevent="toggleSubMenu()"
```

2022-01-11 10:26 UTC, nlepage approved these changes

2022-01-11 10:29 UTC, yannbertrand commented on static/images/flag-be.svg
> +<?xml version="1.0" encoding="UTF-8"?>
Pour info : normalement pas nécessaire sur pix-site avec @nuxt/image qui s'en charge :)

2022-01-11 13:19 UTC, MelanieMEB approved these changes

2022-01-11 13:25 UTC, merged