[FEATURE] Ne plus utiliser l'acronyme "FWB"
1024pix/pix-site pull request #470
Opened 2023-01-16 13:48 UTC by yannbertrand

## :christmas_tree: Problème
On utilise parfois l'acronyme "FWB", parfois le nom complet "Fédération Wallonie-Bruxelles".

## :gift: Proposition
Vu avec Philippine, on harmonise en mettant toujours le mot complet.

## :star2: Remarques
Impacts : 
- Accueil avec sélection de préférence de locale
- Locale Switcher

## :santa: Pour tester
Vérifier qu'on affiche bien "Fédération Wallonie-Bruxelles" dans les éléments précédents.

2023-01-16 14:19 UTC, VincentHardouin commented on config/localization/pix-site.js
>      {
Il manque le changement de ligne 22

2023-01-16 14:20 UTC, yannbertrand commented
Une fois les applications déployées, elles seront accessibles via les liens suivants :

- [Pix Site (.fr)](https://site-pr470.review.pix.fr/)
- [Pix Site (.org)](https://site-pr470.review.pix.org/)
- [Pix Pro (.fr)](https://pro-pr470.review.pix.fr/)
- [Pix Pro (.org)](https://pro-pr470.review.pix.org/)

Les variables d'environnement seront accessibles [ici](https://dashboard.scalingo.com/apps/osc-fr1/pix-site-review-pr470/environment).

2023-01-16 15:55 UTC, yannbertrand commented on config/localization/pix-site.js
>      {
Good catch. C'est corrigé

2023-01-16 16:49 UTC, lego-technix requested changes
Tout me parait bon, juste une petite remarque : serait-il possible d'ajouter un `title` sur le libellé `FWB` qui s'affiche dans le LocaleSwitcher quand on est dans `/fr-be` ? Dans la copie d'écran ci-jointe le pointeur est sur ce libellé `FWB`.

![Screenshot_20230116_174254](https://user-images.githubusercontent.com/109212476/212729594-2052a57e-c4b1-41e7-be3c-abe9154fb8c6.png)

2023-01-17 08:27 UTC, yannbertrand commented
> Tout me parait bon, juste une petite remarque : serait-il possible d'ajouter un `title` sur le libellé `FWB` qui s'affiche dans le LocaleSwitcher quand on est dans `/fr-be` ? Dans la copie d'écran ci-jointe le pointeur est sur ce libellé `FWB`.

C'était un oubli, c'est corrigé :) merci pour l'attention.

2023-01-17 08:38 UTC, lego-technix approved these changes

2023-01-17 08:50 UTC, VincentHardouin approved these changes

2023-01-17 08:53 UTC, merged