[FEATURE] Appeler le service de géolocalisation depuis pix-site (PIX-7036)
1024pix/pix-site pull request #504
Opened 2023-02-15 14:32 UTC by er-lim

## :unicorn: Contexte
Nous avons besoin de géolocaliser les utilisateurs accédant à pix.fr grâce à leur IP. 
Or on ne peut pas connaître l’IP des utilisateurs côté client, il faut donc faire appel à une API qui, en se basant sur son IP, retournera leur géolocalisation (pays).

Ne faire l'appel que sur [pix.fr](https://pix.fr/)

## :robot: Proposition
Faire un appel en asynchrone à l’API de géolocalisation pour récupérer la région géographique de l’utilisateur.  
Passer le résultat dans le layout `default` en attendant que la bannière soit faite.

## :rainbow: Remarques

- Pour éviter de lançer `nginx` en local à chaque développement, la dépendance [@nuxt/proxy](https://github.com/nuxt-community/proxy-module#readme) a été ajouté dans le projet afin de simuler le même comportement. 
Cela ne fonctionne qu'en [local](https://github.com/nuxt-community/proxy-module#features) car on fait le build avec `nuxt generate` et c'est ce qu'on veut !
- En complément, une variable `GEOAPI_HOST` a aussi été ajoutée dans le `.env` pour faire l'appel vers le service de géolocalisation. Elle n'est utilisée que pour @nuxtjs/proxy et donc à ne renseigner qu'en local 😄 

## :100: Pour tester

1. Vérifier dans la console développeur de la review-app de `pix.fr`, qu'il y a bien ce log `shouldShowOutOfFranceBanner` avec une valeur `false` si vous êtes en France, et `true` en dehors.
2. Vérifier, toujours dans la console -> onglet `network`, que l'appel vers le service est bien lancé à chaque chargement de page
3. Dans l'onglet `network` de la console des 3 autres review-apps, voir que le log `shouldShowOutOfFranceBanner` a toujours une valeur `false`

2023-02-16 15:09 UTC, igorissen reviewed
Serait-il possible de découper ce commit ?

2023-02-16 15:16 UTC, er-lim commented on layouts/default.vue
> +      console.log('shouldShowOutOfFranceBanner', this.showOutOfFranceBanner)
A enlever après la review.

2023-02-16 15:27 UTC, er-lim commented
@igorissen C'est découpé 😄

2023-02-16 15:52 UTC, igorissen approved these changes

2023-02-17 07:45 UTC, lego-technix requested changes

2023-02-17 07:45 UTC, lego-technix commented on config/url.js
> + */
Dans tout le code des applications Pix on évite de documenter en utilisant des nommage et des structures de code les plus explicites possibles. Cela ne veut pas dire que toute documentation est interdite. C'est en effet parfois nécessaire. Dans tous les cas on ne mettra jamais de documentation inutile. Donc dans cette documentation il faut retirer « Given Nuxt context, retrieve app base url. » et « @param nuxtContext - Nuxt context. » qui n'apportent rien.

2023-02-17 07:45 UTC, lego-technix commented on config/url.js
> +export function getBaseUrl(nuxtContext) {
Cette variable `nuxtContext` mériterait d'être renommée `context` car on est dans une application Nuxt et le nom de variable `context` s'y rapporte obligatoirement. De plus le reste de la base de code utilise `context` comme nom de variable et il n'y a pas d'autres types de context que le context Nuxt qui sont présents.

2023-02-17 07:55 UTC, lego-technix commented
J'ai modifié la dernière étape de la procédure de test, en modifiant :

> 3.Dans l'onglet `network` de la console des 3 autres review-apps, voir que l'appel vers le service ne fait pas >😸

par :

> 3. Dans l'onglet `network` de la console des 3 autres review-apps, voir que le log `shouldShowOutOfFranceBanner` a toujours une valeur `false`

Cette modification doit être validée par d'autres personnes.

✅ Testé fonctionnellement OK avec un VPN permettant de choisir des points de sortie hors de France sur la base de la dernière étape de la procédure de test modifiée décrite ci-dessus.

2023-02-17 10:28 UTC, er-lim commented on config/url.js
> + */
d'acc, c'est corrigé. Merci pour les informations dessus 🙏

2023-02-17 10:28 UTC, er-lim commented on config/url.js
> +export function getBaseUrl(nuxtContext) {
Bonne remarque ! C'est corrigé.

2023-02-17 13:41 UTC, lego-technix approved these changes

2023-02-20 09:40 UTC, merged