[BUGFIX] Corriger le robots.txt
1024pix/pix-site pull request #508
Opened 2023-02-20 13:10 UTC by er-lim

## :unicorn: Problème
Suite à la mise à jour de la dépendance `@nuxtjs/robots` en version 3.0, le path /robot.txt ne fonctionne plus.  
Un warning est aussi présent lors du lancement de l'app en local : 
```
WARN  Module @nuxtjs/robots is disabled due to incompatibility issues:       
 - [bridge] Nuxt bridge is required
```
Après vérification. La version 3.0 ne supporte plus Nuxt 2 mais uniquement [Nuxt3/Nuxt Bridge](https://github.com/nuxt-community/robots-module/blob/main/CHANGELOG.md#-breaking-changes).

## :robot: Proposition
Rollback la montée de version fait dans cette [PR](https://github.com/1024pix/pix-site/pull/483)

## :rainbow: Remarques
Il y a actuellement un soucis sur la CI sur l'installation des dépendances (en cours d'investigation).

## :100: Pour tester
- Vérifier, sur la review-app, que l'url `/robots.txt` fonctionne bien.

2023-02-20 13:40 UTC, yannbertrand commented
Le `npm ci` fonctionne correctement chez moi.

Sur ce projet, on a configuré [`renovate`](https://github.com/1024pix/pix-site/blob/dev/.github/renovate.json) pour merger automatiquement les montées de version si les tests auto passent. Ce revert ne suffira pas pour empêcher que renovate fasse cette montée de version de nouveau.

Idéalement il faudrait poser un test auto pour qu'on s'assure que ce fichier existe toujours ;) 

A dispo si besoin. (pour info on a un ticket Jira ici : https://1024pix.atlassian.net/browse/PIX-7208)

2023-02-20 13:41 UTC, lego-technix requested changes
Est-ce envisageable d'ajouter un test qui nous protégerait contre toute nouvelle régression sur le /robots.txt à l'occasion de cette PR ?

2023-02-20 13:53 UTC, er-lim commented
> Est-ce envisageable d'ajouter un test qui nous protégerait contre toute nouvelle régression sur le /robots.txt à l'occasion de cette PR ?

@lego-technix Tu penses à un test e2e pour savoir si la route /robots.txt répond ? Si c'est le cas, c'est en cours sur cette [PR](https://github.com/1024pix/pix-site/pull/505/files#diff-261cb7f2cf44e198fcda8230b7edbc8f33c9fd34404905c6751efde0f0162e74) (cc @VincentHardouin) 😸

2023-02-20 13:55 UTC, VincentHardouin commented
@er-lim ma PR de tests e2e ne fonctionne pas, on n'arrive pas à tester du statique

2023-02-22 10:53 UTC, yannbertrand commented
Sera corrigé par #505

2023-02-22 14:21 UTC, er-lim commented
corrigé par https://github.com/1024pix/pix-site/pull/505, je ferme la PR.

2023-02-22 14:21 UTC, closed without merging