[TECH] Stocker le cookie locale au format BCP 47
1024pix/pix-site pull request #520
Opened 2023-03-07 14:30 UTC by er-lim

## :unicorn: Problème
Le cookie `locale` est actuellement stocké en format minuscule. Cela ne correspond pas à l'utilisation des Locale dans le navigateur qui utilise plutôt le format BCP 47.

## :robot: Proposition
Adapter le code pour stocker le cookie sous format BCP 47.

Le support du format minuscule doit être conservé pour la rétro-compatibilité.  

## :rainbow: Remarques
Un polyfills `intl-locale` a été ajouté pour supporter les anciennes version de navigateurs non compatible avec [Intl.Locale](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale)

## :100: Pour tester
A venir.

2023-03-08 10:26 UTC, reibecca approved these changes

2023-03-08 11:46 UTC, lego-technix requested changes

2023-03-08 11:46 UTC, lego-technix commented on package.json
> +    "@formatjs/intl-locale": "^3.1.1",
Déplacer le paquet `@formatjs/intl-locale` dans les `devDependencies` car c'est un devDependency. La procédure pour déterminer quels paquets sont des devDependencies ou pas est décrite dans #472.

2023-03-08 12:17 UTC, lego-technix commented on plugins/locale-observer.js
> +  const localeName = new Intl.Locale(locale).baseName
Utiliser la méthode `Intl.getCanonicalLocales()` dédiée pour accomplir cette action cf. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/getCanonicalLocales

Suggestion de code, qui sera à adapter pour prendre en compte les erreurs possibles :
```suggestion
  const canonicalLocaleName = Intl.getCanonicalLocales(locale)[0]
```

`Intl.getCanonicalLocales()` semble être présente dans tous les navigateurs à supporter tel que décrit dans https://github.com/1024pix/pix/pull/5346 → donc a priori il n'est pas nécessaire de mettre en place un polyfill pour `Intl.getCanonicalLocales()`, alors que c'est bien nécessaire pour `Intl.Locale`.

2023-03-08 13:00 UTC, lego-technix requested changes

2023-03-08 13:00 UTC, lego-technix commented on pages/pix-pro/index.vue
> +        ({ code }) => code.toLowerCase()
Préférer les objets et méthodes natifs fournis par l'objet [`Intl`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl), `Intl.Locale`,  `Intl.getCanonicalLocales()`, etc. aux manipulations.

2023-03-08 13:00 UTC, lego-technix commented on pages/pix-site/index.vue
> +        ({ code }) => code.toLowerCase()
Préférer les objets et méthodes natifs fournis par l'objet [`Intl`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl), `Intl.Locale`,  `Intl.getCanonicalLocales()`, etc. aux manipulations.

2023-03-08 13:06 UTC, lego-technix commented on tests/pages/pix-pro/index.test.js
> +      describe('with international format', () => {
```suggestion
      describe('with value being only one subtag', () => {
```

cf. https://www.rfc-editor.org/rfc/rfc5646.html

2023-03-08 13:07 UTC, lego-technix commented on tests/pages/pix-pro/index.test.js
> +      describe('with BCP47 format', () => {
```suggestion
      describe('with value being in canonical BCP 47 format', () => {
```

2023-03-08 13:14 UTC, lego-technix commented
Je testerai fonctionnellement avec un Firefox 52 installé manuellement à partir de https://ftp.mozilla.org/pub/firefox/releases/52.9.0esr/ une fois que les discussions sur le code seront terminées.

2023-03-09 09:54 UTC, er-lim commented on pages/pix-pro/index.vue
> +        ({ code }) => code.toLowerCase()
d'accord avec toi mais je n'ai pas trouvé pas de fonction qui renvoie la Locale en minuscule.
Je peux aussi l'enlever, ce lowercase a été ajouté dans un cas où on mettrait un code en format BCP47 dans l'app, mais j'anticipe peut être un peu trop 🤔

2023-03-09 16:48 UTC, lego-technix commented on pages/pix-pro/index.vue
> +        ({ code }) => code.toLowerCase()
Pour faire des comparaisons il est préférable de faire des comparaisons sur la base des valeurs canoniques et ne pas chercher à faire des comparaisons sur d'autres bases (par exemple en faisant nous-mêmes des transformations de type `toLowerCase`). Anisi le code correspondant au fait de se baser uniquement sur des valeurs canoniques pourrait avoir une forme dans l'esprit du code ci-dessous (code non-testé) :

```javascript
const chosenLocale = localeCookie.split('=')[1]
const canonicalizedChosenLocale = Intl.getCanonicalLocales(chosenLocale)[0]

const currentLocales = localization.localesForCurrentSite.map(
  ({ code }) => Intl.getCanonicalLocales(code)[0]
)

if (!currentLocales.includes(canonicalizedChosenLocale)) return null

return canonicalizedChosenLocale
```

2023-03-10 09:28 UTC, lego-technix commented on plugins/locale-observer.js
> +  const localeName = Intl.getCanonicalLocales(locale)?.[0]
Utiliser plutôt le nom de variable `canonicalLocale`

2023-03-10 10:18 UTC, er-lim commented on package.json
> +    "@formatjs/intl-locale": "^3.1.1",
j'ai supprimé le polyfills car on utilise `Intl.getCanonicalLocales` supporté par firefox 48 😄

2023-03-10 10:19 UTC, er-lim commented on plugins/locale-observer.js
> +  const localeName = new Intl.Locale(locale).baseName
c'est fait !

2023-03-10 10:20 UTC, er-lim commented on pages/pix-pro/index.vue
> +        ({ code }) => code.toLowerCase()
c'est fait. Merci pour la précision ! 
Remarque : `Intl.getCanonicalLocales` throw une `RangeError` si la ou les chaînes de caractères passées en paramètre sont invalides. J'ai wrappé cette partie dans un `try catch`

2023-03-10 10:20 UTC, er-lim commented on pages/pix-site/index.vue
> +        ({ code }) => code.toLowerCase()
C'est corrigé !

2023-03-10 10:20 UTC, er-lim commented on tests/pages/pix-pro/index.test.js
> +      describe('with international format', () => {
Traité 😸

2023-03-10 10:20 UTC, er-lim commented on tests/pages/pix-pro/index.test.js
> +      describe('with BCP47 format', () => {
c'est fait !

2023-03-10 10:20 UTC, er-lim commented on plugins/locale-observer.js
> +  const localeName = Intl.getCanonicalLocales(locale)?.[0]
C'est fait. Merci pour la remarque !

2023-03-10 17:26 UTC, lego-technix commented on tests/pages/pix-pro/index.test.js
> +      describe('with international format', () => {
Ce point de renommage du `describe` n'a pas été traité ou bien est-ce que je me trompe ?

2023-03-10 17:30 UTC, lego-technix commented on tests/pages/pix-pro/index.test.js
> +      describe('with BCP47 format', () => {
Il me semble qu'il reste un `with BCP47 format` dans le code. La description proposée ci-dessus est un petit peu mieux car elle parle explicitement de « canonical format ».

2023-03-10 17:31 UTC, lego-technix commented
Il me reste à tester avec un Firefox 52. Je m'en charge dès que possible.

2023-03-13 08:32 UTC, lego-technix commented on plugins/locale-observer.js
> +  const canonicalName = Intl.getCanonicalLocales(locale)?.[0]
Ici le nom de variable `canonicalLocale` serait plus adapté et cohérent avec le reste des nommages dans cette PR et les nommages de locales en général.

2023-03-13 08:39 UTC, lego-technix commented on pages/pix-pro/index.vue
> +          ({ code }) => Intl.getCanonicalLocales(code)?.[0]
Écrire `Intl.getCanonicalLocales(chosenLocale)[0]` et non `Intl.getCanonicalLocales(chosenLocale)?.[0]` car cette fonction renverra toujours un tableau non vide, sauf s'il y a une exception.

2023-03-13 08:41 UTC, lego-technix commented on pages/pix-pro/index.vue
> +        )
```suggestion
        const chosenLocale = localeCookie.split('=')[1]
        if (!chosenLocale) return null
                  
        const canonicalChosenLocale =
          Intl.getCanonicalLocales(chosenLocale)[0]
        const canonicalCurrentLocales = localization.localesForCurrentSite.map(
          ({ code }) => Intl.getCanonicalLocales(code)[0]
        )
```

2023-03-13 08:44 UTC, lego-technix commented on pages/pix-site/index.vue
> +        )
Même remarque sur `pages/pix-pro/index.vue`

2023-03-13 08:47 UTC, lego-technix approved these changes
Il reste des petites remarques de nommage et de style à prendre en compte mais à part ça c'est tout bon !

✅ Testé fonctionnellement avec Firefox 52

2023-03-13 15:02 UTC, er-lim commented on tests/pages/pix-pro/index.test.js
> +      describe('with BCP47 format', () => {
Au temps pour moi ! C'est bien fait cette fois-ci 😄

2023-03-13 15:03 UTC, er-lim commented on tests/pages/pix-pro/index.test.js
> +      describe('with international format', () => {
Tu ne te trompes pas 😆 
C'est corrigé !

2023-03-13 15:03 UTC, er-lim commented on pages/pix-pro/index.vue
> +        )
C'est fait !

2023-03-13 15:03 UTC, er-lim commented on pages/pix-site/index.vue
> +        )
Fait aussi 😄

2023-03-13 16:05 UTC, lego-technix commented
Super ! Merci ! C'est mergeable !

2023-03-14 09:34 UTC, merged