[TECH] Remplacer la locale "en-gb" en "en" (PIX-7514)
1024pix/pix-site pull request #538
Opened 2023-05-19 11:54 UTC by er-lim

## ☑️ Reste à faire
- [ ] Mettre à jour les liens dans les documents Prismic en remplaçant `en-gb` par `en` (edit: peut être fait après le merge)

## :unicorn: Problème
Aujourd’hui, la locale _International English_ est gérée sur le site vitrine avec le code `en-gb`. Or ce code représente l’anglais britannique et non l’anglais international qui a pour code `en`. Cela pose aussi d’autres problème de cohérence par rapport aux Pix apps qui elles utilisent la valeur `en` pour la `lang` des utilisateurs.

## :robot: Proposition
Remplacer l’utilisation de la valeur `en-gb` dans le site vitrine par la valeur `en`.

## :rainbow: Remarques

- Une précédente PR a déjà mis en place le remplacement dans le cookie `locale` des valeurs de locales `en-GB` et `en-gb` par `en` :  #522

- La façon de récupérer le document Prismic pour la home de Pix Pro a été modifiée car ne fonctionne plus avec la locale `en`. Cela fonctionnait pour la locale `en-gb` car celui-ici contenait avant l'uid `decouvrir-pix-pro` et Prismic conserve les anciens uid du document. Ce mécanisme va être amélioré dans un prochain ticket.

- La rétrocompatilité a été mise en place pour pouvoir lire les cookies avec une valeur `en-gb` (afin de renvoyer sur le `/en` du site) 😄 

## :100: Pour tester
### Pix Site
- Aller sur la RA .org https://site-pr538.review.pix.org/
- Si vous avez déjà une locale en cookie, cliquez sur International English dans le Locale Switcher. Sinon cliquez sur International English
- Vérifier que le lien est bien https://site-pr538.review.pix.org/en et que la page s'affiche bien en anglais
- Aller sur https://site-pr538.review.pix.org/en-gb et constater que la redirection se fait bien en https://site-pr538.review.pix.org/en.
- Changer la valeur du cookie locale en `en-gb`. 
- Rafraîchir la page et constater que ça fonctionne et que la valeur du cookie locale a été remis en `en`
- Parcourir les liens du menu (Discover Pix, The tests...). 
- Constater que les liens ont, pour le moment, toujours un path en /en-gb
- Cliquer sur les liens et voir que l'url affichée est bien en /en.

### Pix Pro
- Aller sur la RA .org https://pro-pr538.review.pix.org/
- Si vous avez déjà une locale en cookie, cliquez sur International English dans le Locale Switcher. Sinon cliquez sur International English
- Vérifier que le lien est bien https://pro-pr538.review.pix.org/en et que la page s'affiche bien en anglais
- Aller sur https://pro-pr538.review.pix.org/en-gb et constater que la redirection se fait bien en https://pro-pr538.review.pix.org/en.
- Changer la valeur du cookie locale en `en-gb`. 
- Rafraîchir la page et constater que ça fonctionne et que la valeur du cookie locale a été remis en `en`
- Parcourir les liens du menu (Discover Pix Pro, Business...). 
- Constater que les liens ont, pour le moment, toujours un path en /en-gb
- Cliquer sur les liens et voir que l'url affichée est bien en /en.

2023-05-23 09:34 UTC, reibecca commented
**Tests fonctionnels pix-site & pix-pro sur Chrome :** 

- ✅ Aller sur `/en` et vérifier que la page s'affiche bien en anglais
- ✅ Aller sur `/en-gb` et constater que la redirection se fait bien en `/en`
  - ⚠️ Lorsque l'on passe `/en-GB` on est redirigé sur une page d'erreur
- ❌ Changer la valeur du cookie locale en en-gb. Rafraîchir la page et constater que ça fonctionne et que la valeur du cookie locale a été remis en `en` 
  - ➡️ après avoir rafraichi la page, le cookie garde toujours la valeur `en-gb`
- Parcourir les liens du menu (Discover Pix, The tests...) : 
  - ✅ Constater que les liens ont, pour le moment, toujours un path en /en-gb
  - ✅ Cliquer sur les liens et voir que l'url affichée est bien en /en.

2023-05-24 06:44 UTC, lego-technix commented on pages/pix-pro/locale-home.vue
> +const HOME_DOCUMENT_UID_BY_LOCALE = {
Il me semble qu'un nommage de ces différentes variables avec un même préfixe améliorerait la lecture et la cohérence :

```suggestion
const HOME_DOCUMENT_UID_EN = 'discover-pix-pro'
const HOME_DOCUMENT_UID_FR = 'decouvrir-pix-pro'

const HOME_DOCUMENT_UID_BY_LOCALE = {
```

2023-05-24 07:17 UTC, lego-technix commented
> * Lorsque l'on passe `/en-GB` sur pix-site on est redirigé sur une page d'erreur
> 
> * warning Lorsque l'on passe `/en-GB` sur pix-pro on est redirigé sur `https://pro-pr538.review.pix.org/fr/en-GB` et la page "Oups" apparaît

Je ne pense pas que devoir gérer des URL de la forme `/en-GB` soit à faire car ces URL n'ont jamais existé il me semble.

2023-05-24 07:20 UTC, lego-technix requested changes
Comme l'a déjà noté @reibecca, si on est sur une page (comme http://dev.pix.org/en/the-tests/) et qu'on recharge cette page ou bien qu'on navigue sur une autre page, un cookie avec la valeur `en-gb` garde cette valeur au lieu d'avoir sa valeur modifiée en `en`.

À part ce point, le reste est super 😃

2023-05-25 07:16 UTC, er-lim commented
@reibecca @lego-technix J'ai ajouté, dans les derniers commits, la gestion du cookie locale avec une valeur `en-GB`. Lorsque qu'un visiteur arrive sur la page et qu'il avait déjà un cookie avec cette valeur là, le cookie sera bien mis à jour avec une valeur `en`.

Je vous laisse tester 😄

2023-05-25 08:44 UTC, lego-technix approved these changes

2023-05-25 08:44 UTC, lego-technix commented on services/cookie.js
> +}
Super ce cookie service ❤️

Juste quelques suggestions, non-bloquantes donc :

1. Je trouve que protéger l'utilisation de la fonction contre un `name` _falsy_ ou une `value` _falsy_ laisse penser que ce sont des usages qui existent dans le code du projet. Or ces usages n'existent pas et n'arriveront clairement pas. Au besoin un jour on pourra tout au plus faire un `deleteCookie`.
2. Ce service étant générique, nommons les propriétés de manière générique

```suggestion
function setCookie(name, value, isDev) {
  const cookieProperties = [
    `${name}=${value}`,
    'path=/',
    'max-age=31536000',
    'SameSite=Strict',
  ]

  if (!isDev) {
    cookieProperties.push(`domain=${config.siteDomain}`)
  }

  document.cookie = cookieProperties.join('; ')
}
```

2023-05-25 08:44 UTC, lego-technix commented
✅ Testé fonctionnellement avec succès avec Firefox

2023-05-25 09:33 UTC, reibecca commented
> > * Lorsque l'on passe `/en-GB` sur pix-site on est redirigé sur une page d'erreur
> > * warning Lorsque l'on passe `/en-GB` sur pix-pro on est redirigé sur `https://pro-pr538.review.pix.org/fr/en-GB` et la page "Oups" apparaît
> 
> Je ne pense pas que devoir gérer des URL de la forme `/en-GB` soit à faire car ces URL n'ont jamais existé il me semble.

Actuellement en production si tu vas sur pix-site ou pix-pro en `.org` et que tu sélectionnes la locale International English tu tombe sur un URL avec `/en-gb`. Et si tu le modifies en écrivant `/en-GB` tu ne tombes pas sur page d'erreur, tu restes bien sur la page en anglais. Donc j'ai l'impression qu'il faut gérer ce cas ici.

2023-05-25 09:34 UTC, reibecca commented
✅ Testé fonctionnellement à nouveau sur Chrome et c'est bon pour le cookie 😄

2023-05-25 09:36 UTC, reibecca approved these changes

2023-05-25 09:37 UTC, lego-technix commented
> Actuellement en production si tu vas sur pix-site ou pix-pro en `.org` et que tu sélectionnes la locale International English tu tombe sur un URL avec `/en-gb`. Et si tu le modifies en écrivant `/en-GB` tu ne tombes pas sur page d'erreur, tu restes bien sur la page en anglais. Donc j'ai l'impression qu'il faut gérer ce cas ici.

Personne n'est censé modifier un URL en `/en-gb` pour le changer en `/en-GB`. Et il n'y a jamais eu de contenus publiés sur Prismic dans une locale avec la valeur `en-GB` (c'est d'ailleurs un, tout petit, problème de leur implémentation : Prismic n'utilise pas la valeur canonique recommandée par les RFC). Alors que pour les cookies c'est différent : les différentes valeurs `en-gb` et `en-GB` se sont retrouvées dans les cookies des visiteurs au fur et à mesure des évolutions que nous avons faites.

2023-05-25 10:08 UTC, er-lim commented
> > Actuellement en production si tu vas sur pix-site ou pix-pro en `.org` et que tu sélectionnes la locale International English tu tombe sur un URL avec `/en-gb`. Et si tu le modifies en écrivant `/en-GB` tu ne tombes pas sur page d'erreur, tu restes bien sur la page en anglais. Donc j'ai l'impression qu'il faut gérer ce cas ici.
> 
> Personne n'est censé modifier un URL en `/en-gb` pour le changer en `/en-GB`. Et il n'y a jamais eu de contenus publiés sur Prismic dans une locale avec la valeur `en-GB` (c'est d'ailleurs un, tout petit, problème de leur implémentation : Prismic n'utilise pas la valeur canonique recommandée par les RFC).
> 
> Alors que pour les cookies c'est différent : les différentes valeurs `en-gb` et `en-GB` se sont retrouvées dans les cookies des visiteurs au fur et à mesure des évolutions que nous avons faites.

La remarque de @reibecca  est intéressante car en effet si https://pix.org/en-gb et https://pix.org/en-GB sont accessibles et donc référencées (possiblement contenu dupliqué d'ailleurs...) , il faut aussi rediriger le trafic de `/en-GB` vers `/en` nn ? 🤔 
Je parles surtout du point de vue SEO 😄

2023-05-25 10:11 UTC, lego-technix commented
> La remarque de @reibecca est intéressante car en effet si https://pix.org/en-gb et https://pix.org/en-GB sont accessibles et donc référencées (possiblement contenu dupliqué d'ailleurs...) , il faut aussi rediriger le trafic de `/en-GB` vers `/en` nn ? thinking
> Je parles surtout du point de vue SEO

Je répondais précisément à ce point : il n'y a jamais jamais jamais eu de contenu en ligne commençant par l'URL  `https://pix.org/en-GB`. Et c'est une certitude car Prismic ne le permet pas.

Évidemment si de tels URL avaient existé nous aurions fait les redirections pour ces URL aussi de manière à être le mieux possible en terme de SEO.

2023-05-25 10:16 UTC, lego-technix commented
Et je dirais même : effectuer des redirections pour des URL commençant par `/en-GB` (par exemple `https://pix.org/en-GB`, etc.) pourrait induire en erreur les développeurs faisant des évolutions/maintenance sur le projet en leur laissant penser qu'il y a eu des contenus avec `en-GB` dans l'URL et qu'il y a eu des contenus avec la locale `en-GB` dans Prismic. Ce qui n'a jamais été le cas.

2023-05-25 10:27 UTC, er-lim commented
> Et je dirais même : effectuer des redirections pour des URL commençant par `/en-GB` (par exemple `https://pix.org/en-GB`, etc.) pourrait induire en erreur les développeurs faisant des évolutions/maintenance sur le projet en leur laissant penser qu'il y a eu des contenus avec `en-GB` dans l'URL et qu'il y a eu des contenus avec la locale `en-GB` dans Prismic. Ce qui n'a jamais été le cas.

<img width="1437" alt="Capture d’écran 2023-05-25 à 12 25 11" src="https://github.com/1024pix/pix-site/assets/11760574/c57d9d15-32bb-4986-a235-edfb8efd685e">
  
  
En effet, on tombe sur une 404 ce qui valide ton hypothèse. L'URL n'existe pas 👍 
Complètement d'accord pour ne pas traiter ce cas là 😄

2023-05-25 15:16 UTC, er-lim commented on services/cookie.js
> +}
En effet, j'avais mis ce check en pensant que cette fonction allait être un utilitaire. Ce qui n'est pas le cas vu qu'on importe `config`. 
C'est retiré. J'en ai aussi profité pour mettre à jour le nom de la variable `cookieProperties` 😄

2023-05-26 07:46 UTC, merged