[BUGFIX] Rendre actif les liens des locale international sur localeSwitcher du burger menu (PIX-8244).
1024pix/pix-site pull request #545
Opened 2023-06-09 15:38 UTC by Thomasevano

## :unicorn: Problème
Les locales international ne possèdent pas la class `locale-switcher-burger-menu__list--active`

## :robot: Proposition
Modifier la condition d'ajout de la class

## :rainbow: Remarques
Les locales international regroupées ensemble dans un sous tableau, d'ou le besoins de `child` on va chercher dans cet objet.
On pourrait modifier cette structure de données afin de les mettre au meme niveau que les autres locales, plutôt que de changer la condition .

## :100: Pour tester
- Se rendre sur 
- Naviguer entre toutes les locales
- Vérifier que lien comporte bien la class `locale-switcher-burger-menu__list--active`

2023-06-12 07:42 UTC, igorissen commented on components/LocaleSwitcher/LocaleSwitcher.vue
**Suggestion** :

Ce ne serait pas mieux de partir sur une propriété de type `computed` qui aura une structure adaptée dans le cas de la version mobile ? Cela rajoutera un peu de logique mais cela évite d'avoir trop de condition dans le template.

2023-06-12 08:22 UTC, er-lim commented on components/LocaleSwitcher/LocaleSwitcher.vue
Je rejoins @igorissen, ça permettra d'améliorer la lisibilité du template !

2023-06-12 14:57 UTC, reibecca commented on tests/config/localization/pix-pro.test.js
> +    it('should return all menu entries for pix-pro', () => {
on peut supprimer le should dans le titre du test

2023-06-12 15:02 UTC, reibecca commented on tests/config/localization/pix-pro.test.js
> +      // then
```suggestion
      // when & then
```

2023-06-13 12:53 UTC, lego-technix requested changes

2023-06-13 12:53 UTC, lego-technix commented on config/localization/pix-pro.js
> +  ],
Il est dommage que `menuForMobile` soit quasiment une copie de `menu`. Avoir cette quasi-duplication de code rend la maintenance plus difficile et est une source d'erreur.

`menuForMobile` pourrait être obtenu à partir de `menu` en en faisant une « copie à plat ». Cela semble être une mission pour https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap . Et un bon document sur l'utilisation de `Array.flatMap` : https://2ality.com/2022/05/processing-arrays-non-destructively.html#the-array-method-.flatmap()

2023-06-13 12:53 UTC, lego-technix commented on config/localization/pix-site.js
> +  ],
Il est dommage que `menuForMobile` soit quasiment une copie de `menu`. Avoir cette quasi-duplication de code rend la maintenance plus difficile et est une source d'erreur.

`menuForMobile` pourrait être obtenu à partir de `menu` en en faisant une « copie à plat ». Cela semble être une mission pour https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap . Et un bon document sur l'utilisation de `Array.flatMap` : https://2ality.com/2022/05/processing-arrays-non-destructively.html#the-array-method-.flatmap()

2023-06-13 12:53 UTC, lego-technix commented on components/LocaleSwitcher/LocaleSwitcher.vue
> +        v-for="menuItem in menuForMobile"
Globalement les noms « ForMobile » ne sont pas très adaptés dans le cadre actuel de pix-site car on obtient l'affichage du burger menu quand la zone d'affichage est réduite en largeur, ce qui arrive facilement sur environnement de bureau et n'est donc pas spécifique aux environnements mobiles. Enfin sur mobile on peut aussi orienter l'écran dans une autre direction et potentiellement bénéficier à nouveau d'une zone d'affichage plus large.

Aussi voici des suggestions de nommage à utiliser à la place de « ForMobile » :
* shortWidth
* shortWidthDisplay
* etc.

2023-06-13 13:06 UTC, igorissen commented on components/LocaleSwitcher/LocaleSwitcher.vue
> +        v-for="menuItem in menuForMobile"
Je comprends ton point de vue et je pense qu'il est le bon mais ce sera compliqué de modifier le terme `mobile` qui est fortement lié aux petits tailles d'affichage, d'où le faite que l'on est pris le choix d'utiliser `menuForMobile`.

Si on introduit le terme `short` alors il faudra créer un autre ticket (ou plusieurs) pour retirer complètement le terme `mobile` de notre vocabulaire.

2023-06-13 13:09 UTC, igorissen commented on config/localization/pix-pro.js
> +  ],
On avait le choix entre la solution implémentée et celle dont tu mentionnes (au niveau du fichier de configuration ou une propriété de type computed).

On a fait ce choix pour avoir quelque chose de statique et de rapide.

2023-06-13 13:11 UTC, reibecca commented on components/LocaleSwitcher/LocaleSwitcher.vue
> +        v-for="menuItem in menuForMobile"
Je ne sais pas si à sa place dans cette PR mais est-ce qu'on pourrait renommer le `type === 'only-text'` qui correspond au LanguageSwitcher avec l'affichage direct et sans dropdown ? Je pensais justement à un terme avec 'mobile' 😅

2023-06-13 13:13 UTC, lego-technix commented on components/LocaleSwitcher/LocaleSwitcher.vue
> +        v-for="menuItem in menuForMobile"
Il n'y a qu'une dizaine d'utilisations du mot « mobile » dans le code avant cette PR et qui est presque exclusivement `large-mobile`. Donc cela fait peu d'utilisation. Évitons d'en augmenter la proportion.

En refaisant des `grep` dans le code on trouve qu'il y a déjà le breakpoint `large-screen`, donc plutôt que les `shortWidth` et `shortWidthDisplay` que je proposait on pourrait alors plutôt utiliser `small-width-screen`, `narrow-screen`, etc.

2023-06-13 13:15 UTC, Thomasevano commented on components/LocaleSwitcher/LocaleSwitcher.vue
> +        v-for="menuItem in menuForMobile"
Et pourquoi pas `small-screen` ? 😯

2023-06-13 13:18 UTC, lego-technix commented on components/LocaleSwitcher/LocaleSwitcher.vue
> +        v-for="menuItem in menuForMobile"
`small-screen` ne dit pas dans quel sens c'est « small », ça laisse même plutôt penser que c'est « small » « dans tous les sens ». Alors que le comportement que nous ciblons est une zone d'affichage d'une petite largeur.

2023-06-13 13:21 UTC, lego-technix commented on config/localization/pix-pro.js
> +  ],
Faire une copie à plat ne me semble pas trop difficile. L'état actuel du code de pix-site a déjà un certain nombre de duplications 😢 et il serait vraiment dommage/pénible d'en ajouter plus. Je peux fournir une proposition de copie à plat si besoin.

2023-06-13 13:52 UTC, Thomasevano commented on config/localization/pix-pro.js
> +  ],
J'ai fais un 
```localization.menuForMobile = localization.menu.flatMap(
  (menuItem) => menuItem.children || menuItem
)```
Qu'en penses-tu ?

2023-06-13 14:05 UTC, lego-technix commented on config/localization/pix-pro.js
> +  ],
Je trouve cela très satisfaisant @Thomasevano 👍

2023-06-13 14:06 UTC, lego-technix approved these changes

2023-06-13 14:07 UTC, lego-technix commented on config/localization/pix-site.js
> +  ],
Point résolu avec l'utilisation de flatMap.

2023-06-13 14:34 UTC, igorissen approved these changes

2023-06-13 14:45 UTC, reibecca approved these changes

2023-06-14 08:32 UTC, merged