[TECH] Initial Dockerfile to host pix-site in scalway
1024pix/pix-site pull request #652
Opened 2024-05-03 08:00 UTC by alipix

## :unicorn: Problème
Hébérger pix-site chez un autre provider 

## :robot: Proposition

## :rainbow: Remarques

## :100: Pour tester
CI en vert

2024-05-07 09:06 UTC, BerengereC commented
Les logs d'accès étaient visibles avant sur scalingo et ne le sont plus :-(

2024-05-14 09:55 UTC, VincentHardouin requested changes, later dismissed

2024-05-14 09:55 UTC, VincentHardouin commented on Dockerfile
> +RUN npm run build
Il faut plutôt utiliser `npm ci` qui lui utilisera les versions lockées des packages. 

```suggestion
ENV SITE=pix-site

WORKDIR /code/shared
RUN npm ci

WORKDIR ../pix-site
RUN npm ci
RUN npm run build
```

2024-05-14 09:55 UTC, VincentHardouin commented on Dockerfile
> +RUN chown -R nginx:nginx /app/
Pour s'éviter ça, je propose de plutôt utiliser le dossier par défaut de nginx et de supprimer la configuration spécifique. 
C'est à dire : 
- ligne 23 on revient à ce qui est dans [la documentation](https://hub.docker.com/_/nginx) :
```
COPY --from=build-stage /code/pix-site/build /usr/share/nginx/html
```
- Ensuite, on supprime la ligne 26 de fichier 
- Enfin, on modifie la ligne 66 du `servers.conf`.

2024-05-14 09:55 UTC, VincentHardouin commented on Dockerfile
> +COPY --from=build-stage /code/pix-site/nginx.conf /etc/nginx/conf.d/pix-site.conf
La doc copie le fichier dans `defaut.conf` et si on utilise les templates dans `templates/default.conf.template`. Je vois pas l'intérêt que ça apporte de changer le nom du fichier à part devoir rajouter du spécifique avec la ligne 27 de ce fichier

2024-05-14 09:55 UTC, VincentHardouin commented on Dockerfile
> +RUN erb servers.conf.erb > nginx.conf
Le templating par defaut du buildpack nginx est bien erb, ce n'est cependant pas le cas de base pour Docker. 

Ici on se retrouve à installer ruby pour faire nos affaires, alors que la solution proposée par nginx est d'utiliser les templates (cf: https://hub.docker.com/_/nginx section "Using environment variables in nginx configuration (new in 1.19)")

2024-05-14 09:55 UTC, VincentHardouin commented on Dockerfile
> +FROM nginx:alpine AS run-stage
Ici, il manque une version de nginx, pinner les versions qui doivent être utiliser en production me semble primordial

2024-05-15 09:08 UTC, yoandl commented on Dockerfile
> +COPY --from=build-stage /code/pix-site/nginx.conf /etc/nginx/conf.d/pix-site.conf
C'est en effet une bonne pratique d'utiliser les templates. 
Cependant comme nous devons déployer le service sur 2 hébergeurs ça nous oblige à gérer 2 fichiers "template", un côté buildpack l'autre côté docker, sauf que nous avons des choses à modifier régulièrement en ce moment dans ce fichier.

Ce que cette pratique nous apporterait c'est de modifier à chaud des variables et de les appliquer uniquement sur le nouvel hébergeur.
Si on garde la pratique actuelle avec ruby, on doit juste rebuild le container et ça change rien à notre config "centralisée".

Dans un second temps on pourrait penser à revoir le fonctionnement si on reste uniquement sur du docker.

2024-05-17 13:51 UTC, MathieuGilet approved these changes

2024-05-17 13:54 UTC, BerengereC approved these changes

2024-05-17 13:57 UTC, yoandl approved these changes
LGTM

2024-05-17 14:00 UTC, merged